### PR TITLE
Enable `DeserializationFeature.READ_ENUMS_USING_TO_STRING` by default (3.0)

### PR DESCRIPTION
**Pull request by JooHyukKim**
Implements [JSTEP-2 > DeserializationFeature](https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-2#deserializationfeature)

### CODE REVIEW

**Comment by JooHyukKim** [comment]
Re-running CI because of Fuzzer failure (was nearly impossible to read log, due to its enormous volume)

**Comment by JooHyukKim** [comment]
Fuzzer is failing at build stage with import error.
Anyone seen this before? 🤔

image

**Comment by cowtowncoder** [comment]
I do not recall seeing that error, but I also haven't been paying attention to Fuzzer action.

I think I should just go ahead and disable it, seems to have little value and I think OSS-Fuzz runs their generation elsewhere anyway.

**Comment by cowtowncoder** [comment]
Will review this and #4567 later today, get merged. Good stuff!

**Review by cowtowncoder — APPROVED** [review]

**Review by cowtowncoder — APPROVED** [review]

**Comment by JooHyukKim** [comment]
Will update JSTEP-2 Wiki accordingly.
For this PR and one for `SerializationFeature`

**Comment by JooHyukKim** [comment]
Will update JSTEP-2 Wiki accordingly.
For this PR and one for SerializationFeature

cc. @cowtowncoder

**Comment by cowtowncoder** [comment]
I did some updates but may have missed something so appreciate your help @JooHyukKim.

**Comment by JooHyukKim** [comment]
>  I did some updates but may have missed something so appreciate your help @JooHyukKim.

I checked and everything is there 👍🏼

**Comment by Karl255** [comment]
Hello, looking through [JSTEP2](https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-2) to understand the changes to jackson defaults I noticed that this and the sibling feature don't have the rationale mentioned anywhere. What's the rationale behind this changed default?

**Comment by cowtowncoder** [comment]
@Karl255 I think it was requested by multiple users -- but in general seemed like the way to go as default handling for "vanilla" Enums is the same either way (`Enum.name()` used by default `toString()`) but you cannot override `name()` whereas you can override `toString()` to customize handling.

**Comment by JooHyukKim** [comment]
Thanks @Karl255 ! I’ll think I accidentally pointed JStep doc and issue to the wrong place.
I created issue for it.
May pick the work back up in a few days.

Good if u could hep as well! Thanks

**Comment by Karl255** [comment]
I wasn't able to find anything related to this myself, which is why I asked in the first place.

I'll also mention that this creates an issue with Java's built-in ChronoUnit enum, as the toString() returns for example "Minutes" instead of "MINUTES" as name() does. It's something that we have to handle in our codebase now, though we probably shouldn't be storing Java's enums in the first place :smile:

**Comment by cowtowncoder** [comment]
Ah, too bad about `ChronoUnit` that is unfortunate. Thank you for sharing the details!

**Pull request merged**
