### PR TITLE
Fix #1737 on 2.6 branch

### LINKED ISSUE #1737: Block more JDK types from polymorphic deserialization
(note: follow-up for #1599)

After initial set of types blocked new reports have arrived for more black-listing.
Although eventual approach is likely to rely separate module (for more timely updates and wider version coverage), at this point addition in databind is needed.

I will update specific list of additions once complete and release is out. Target versions are `2.8.10` and `2.9.1` -- it is possible to backport in 2.7 and even 2.6, but there is diminishing return on effort with those versions so it will not happen unless specifically requested (I'm happy to merge PRs).

### PR DESCRIPTION
**Pull request by derekstraka**
#1737 fixes CVE 2017-15095 apply this on 2.6 as well for if/when the next release occurs.

### CODE REVIEW

**Comment by derekstraka** [comment]
@poverma - FYI

**Comment by cowtowncoder** [comment]
Thanks! Will add a note on https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.6.7.x as well, if `2.6.7.2` release is desired -- let me know if and when, micro-patches are easy enough.
I am now trying to add `CVE` tag for issues, prs.

**Comment by derekstraka** [comment]
@cowtowncoder - We'd appreciate a release since we have some open source projects that are resisting the update to 2.7.X for some reason, hence the backport of this fix.  Thanks!

**Comment by ScrapCodes** [comment]
https://github.com/advisories/GHSA-h592-38cm-4ggp Seems to indicate, the version 2.6.7.3 is affected. Is it that the advisories data is out of date? What is the way to update it.

**Comment by cowtowncoder** [comment]
@ScrapCodes as per my other comment, I do not know how to do anything about that, but as per 

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.6.7.x

issue was fixed in 2.6.7.2.

**Pull request merged**
