### PR TITLE
Using JsonCreator cause generating invalid path reference in JsonMappingException

### PR DESCRIPTION
**Pull request by Kamil-Benedykcinski**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks good to me!

One process thing before I can merge this: before the first contribution, we need to get a Contributor License Agreement. It's a one-page document:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and just needs to be filled with info on contributor, project (Jackson) and signed.
Easiest way is usually to print, scan, email to `info` at fasterxml dot com.

Once we have that I can merge this in, and CLA is valid for any and all contributions you make for all Jackson projects. It's a bit of pain but fortunately the only thing we need to track to keep corporate users of the library happy. :)

So, if you can do that when you get a chance, that would be great.
Thank you again for the contribution!

**Comment by Kamil-Benedykcinski** [comment]
CLA has been sent:)

**Comment by Kamil-Benedykcinski** [comment]
When will be next version released?

**Comment by cowtowncoder** [comment]
Ah, did not notice there was separate PR for 2.5. Since this should be safe, will merge this as well.

As to next version: 2.6.0-rc2 within a week or two (and final 2.6.0 within 2-3 weeks).
Probably similarly for 2.5.4.

**Comment by Kamil-Benedykcinski** [comment]
Thanks!

**Pull request merged**
