### PR TITLE
Fix #924 - SequenceWriter.writeAll() could accept Iterable

### LINKED ISSUE #924: SequenceWriter.writeAll() could accept Iterable
Currently the method from ${subject} looks like this:

```java
public <C extends Collection<?>> SequenceWriter writeAll(C container) throws IOException {
        for (Object value : container) {
            write(value);
        }
        return this;
    }
```

The only assumption on the container is therefore it can be iterated through it using the for each loop. That being said, the signature can be weaken to accept also the `? extends Iterable`. Could you please change it to 

```java
public <I extends Iterable<?>> SequenceWriter writeAll(I iterable) throws IOException {
        for (Object value : iterable) {
            write(value);
        }
        return this;
    }
```

Collection extends Iterable, hence no API-breakage.

### PR DESCRIPTION
**Pull request by Jiri-Kremser**
see issue #924

### CODE REVIEW

**Comment by cowtowncoder** [comment]
As per discussion, what would work better would be to add a new overload, but keep the old as well.
This way binary compatibility would be retained. Old method could/should then be marked as deprecated.

If method is simply changed, class loader could fail if code was compiled against older Jackson version, but loaded against newer. Class loader does not consider overloads or anything more sophisticated than simple match of type-erased method signatures.

**Comment by Jiri-Kremser** [comment]
@cowtowncoder I've added the new method and deprecated the old one, there is also 1 simple unit test.

btw. the travis is failing because of a different reason (it can't compile Java 7 constructs with jdk6)

**Comment by cowtowncoder** [comment]
Thanks -- I ended up changing it as suggested, although with manual merging. Thank you again for the suggestion, will be included in 2.7.0.

**Comment by Jiri-Kremser** [comment]
:+1: thanks

**Pull request closed without merging**
