### PR TITLE
Sliced ByteBuffer's Array Offset not respected #1662

### PR DESCRIPTION
**Pull request by marc-christian-schulze**
Fix for #1662

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
Shouldn't proposed changes be synchronized with the following code for non-array based byte buffers?
```
        ByteBuffer copy = bbuf.asReadOnlyBuffer();
        if (copy.position() > 0) {
            copy.rewind();
        }
```

**Comment by marc-christian-schulze** [comment]
Any chance to get this in 2.9.8? Would like to have this asap available.

**Comment by cowtowncoder** [comment]
Right now I am swamped with work and have unfortunately little time to work on Jackson. But we'll see. I can't promise any specific date at this point, and it is unlikely 2.9.8 specifically would be released during October.

I am bit unsure if the change is safe enough to include in 2.9, however, and was considering it to go in 2.10.0 instead to reduce any risk of regression.

**Comment by marc-christian-schulze** [comment]
There are only two code paths leading to the change line:

1. an array-backed ByteBuffer with offset of 0
2. an array-backend ByteBuffer with offset > 0

For 1) there was already a unit tests and for 2) I created one that, if you remove my one line of change, will fail. So IMHO there's a negligible risk by publishing this change.

**Comment by cowtowncoder** [comment]
@marc-christian-schulze Ok. `ByteBuffer` API has always been confusing to me so I will trust you understand it better and that this is legit. Merging to be included in 2.9.8. Thank you!

**Comment by cowtowncoder** [comment]
@marc-christian-schulze Ok. `ByteBuffer` API has always been confusing to me so I will trust you understand it better and that this is legit. Merging to be included in 2.9.8. Thank you!

**Comment by cowtowncoder** [comment]
@marc-christian-schulze Ok. `ByteBuffer` API has always been confusing to me so I will trust you understand it better and that this is legit. Merging to be included in 2.9.8. Thank you!

**Comment by cowtowncoder** [comment]
@marc-christian-schulze Ok. `ByteBuffer` API has always been confusing to me so I will trust you understand it better and that this is legit. Merging to be included in 2.9.8. Thank you!

**Comment by cowtowncoder** [comment]
Would merge but Github is having... issues... it seems :-(

**Comment by cowtowncoder** [comment]
Hmmh. Ok, didn't notice it's for master. Need to manually merge.

**Pull request merged**
