### PR TITLE
add extra contructor to AsArraySerializerBase

### PR DESCRIPTION
**Pull request by pjfanning**
The constructor forward fit from 2.12 is not what I need for jackson-module-scala. I need something more like this one.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
I can add a new one but just to make sure added one won't work...

1. I'll change `JsonSerializer<Object> elementSerializer` to `JsonSerializer<?> elementSerializer` and do cast in constructor (no need to require casting by caller here)
2. While I am ok in taking `JavaType` as first argument, that really should not be element type but the container type. It is just metadata and not used much currently, but hope is to make more use of it. So I think separate parameter is needed
3. Ordering of `TypeSerializer` and `BeanProperty` should probably be retained for consistency.

So I guess I am wondering more about what exactly is missing?

**Comment by pjfanning** [comment]
Scala doesn't work well with the 2 separate types of constructor that AsArraySerializerBase has. One set that has type metadata but doesn't let you set the BeanProperty and another set that let's you set a parent serializer and the BeanProperty. What I need is a constructor that allows you to set the type metadata and the BeanProperty.

**Comment by cowtowncoder** [comment]
As background, there is a specific reason why `BeanProperty` is not passed in default constructors -- it is typically only available through `createContextual()`, which usually is called to sort of refine existing (non-contextual) (de)serializer.

But there are cases where contextualization may change the type so I am not against having constructor(s) that allow passing both.

What I am trying to see is just the minimal new constructor that follows the convention of existing ones. For that, I think:

1. `Class<?>` for parent container erased type (`Collection.class`) is needed separately (even if caller passes "too general" type like `Object.class) -- this is different from element type
2. `BeanProperty` added
3. Use same relative ordering of parameters of similar constructors.

and it'd be one that does not take "base" (existing serializer).

**Comment by pjfanning** [comment]
sounds good - can you make the change and I'll test it out?

**Comment by cowtowncoder** [comment]
Sure, will go and add something later tonight.

**Comment by cowtowncoder** [comment]
Oh actually, the method added in 2.12:

```
    protected AsArraySerializerBase(Class<?> cls, JavaType elementType, boolean staticTyping,
            TypeSerializer vts, BeanProperty property, JsonSerializer<?> elementSerializer,
            Boolean unwrapSingle)
    {
```

would seem like match, as long as you pass type-erased container type? I did change `elementSerializer` singature to have `<?`> parameter over `<Object>` (less casting by caller) but otherwise that should do it?
You can just pass `Object.class` as first argument if container type is not known, although ideally it should be the type-erased type.

**Comment by pjfanning** [comment]
@cowtowncoder is the latest change ok?

**Comment by cowtowncoder** [comment]
@pjfanning Yes wrt `CollectionSerializer`, but the other constructor already exists just with 2 arguments in different order, so I was thinking no alternative was needed... Oh! The problem there is that "property" is not passed!
I'll fix that.

**Comment by cowtowncoder** [comment]
(ignore previous, now deleted comment -- was looking at 2.12 but this is for master)

**Comment by cowtowncoder** [comment]
I think I will reorder arguments slightly in that base class to make them consistent -- apologies for the mess. Will add a note when this should be in order.

**Comment by cowtowncoder** [comment]
Changes made: I hope order of parameters can now be stable... it's bit arbitrary of course and I am not happy about having to pass that many parameters but it is what it is.

**Comment by pjfanning** [comment]
Thank. I can name the parameters in the scala call - scala supports this and when you name them, the order of the params doesn't matter, just the names.

**Comment by cowtowncoder** [comment]
Ok I think recompilation might still be needed; new version of jackson-databind 3.0.0-SNAPSHOT deployed and Scala module master does not compile due to reordering, I think.

**Pull request merged**
