### PR TITLE
Add a failing a unit test for #3647: incompatibility of @JsonIgnoreProperties and @JsonValue annotations.

### PR DESCRIPTION
**Pull request by mukham12**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@mukham12 I'll need CLA if there's eventual PR (it's here https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf) but I can merge test-only changes now.
Thank you!

**Comment by mukham12** [comment]
Hi @cowtowncoder,

Absolutely! I am eagerly anticipating the moment when I'll be able to submit a PR. To that end, I created a failing test case like you suggested in one of the comment threads. However, with my plate already full and the need to become more familiar with the codebase, I can't say for certain when I'll be able to check in my changes. But I can still sign the agreement if it’s mandatory. Do I email the agreement to you once I fill it out?

**Comment by cowtowncoder** [comment]
@mukham12 Right; if you end up doing PR, CLA needs to be sent to `info` at fasterxml dot com.
(the usual way is to print it, fill & sign, scan/photo, then email). CLA not needed for small test code changes or document updates so this is just in case you end up submitting code change.

No hurry with work, this may not be trivial to do (... or sometimes it is simpler than I think, it all depends on luck :) )

**Comment by mukham12** [comment]
Tatu (is it okay if I refer to you like this?),

Gotcha! I will try to send that over as soon as I get a chance.

Thanks,

**Comment by cowtowncoder** [comment]
@mukham12 Yep, perfectly fine. I'm no Clark Kent :)

**Pull request merged**
