### PR TITLE
Allow more control over default creator property values

### PR DESCRIPTION
**Pull request by michaelhixson**
~~Don't merge this (yet)!~~

This is following up on a previous discussion in jackson-module-kotlin: https://github.com/FasterXML/jackson-module-kotlin/issues/26

I haven't bothered with javadoc and tests yet because I'm wondering if this is a good approach in general.  It's the best solution I could come up with, and it does solve the original problem I was having, but who knows what problems a Jackson expert might spot.  Should I keep moving forward with this approach?

*Update:* This PR is now complete from my perspective.  Please review and/or merge when you like.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ok. I think that giving more responsibility for `ValueInstantiator` makes sense, and approach here would also be backwards compatible. So I think that's a good approach, with pieces shown.

**Comment by michaelhixson** [comment]
@cowtowncoder Thanks for the review.  I'll get to work on the javadocs and tests then.  Will ping you when that's in place.

**Comment by michaelhixson** [comment]
@cowtowncoder I added some javadoc and tests.  Mind taking a look?

If this gets merged then I will start working on the PR for the Kotlin module.

**Comment by apatrida** [comment]
Why is the test casting to `StdValueInstantiator` instead of using `ValueInstantiator`?

**Comment by michaelhixson** [comment]
They cast to `StdValueInstantiator` so that they can use the constructor that requires that type.

http://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/deser/std/StdValueInstantiator.html#StdValueInstantiator(com.fasterxml.jackson.databind.deser.std.StdValueInstantiator)

**Comment by apatrida** [comment]
Yes, I saw then when updating Jackson-Kotlin module, so have it check that it is actually that type before casting, then raising exception if something unexpected happens in future implementation with what type is received.

**Comment by apatrida** [comment]
@michaelhixson can this backport to 2.7.x?

**Comment by michaelhixson** [comment]
@apatrida I think so.

**Comment by cowtowncoder** [comment]
I don't think that can be done as this opens up new API to call. Such changes should be reserved to new minor versions.

**Pull request merged**
