### PR TITLE
Fix #3053 (Serialize enums to lowercase)

### LINKED ISSUE #3053: Allow serializing enums to lowercase (`EnumFeature.WRITE_ENUMS_TO_LOWERCASE`)
**Is your feature request related to a problem? Please describe.**
Java enums are usually defined as `UPPER_CASE_WITH_UNDERSCORE`. This is not a standard in endpoints, as these rather use `lower_case_with_underscore`. There is already feature for `ACCEPT_CASE_INSENSITIVE_ENUMS`, which helps with deserialization, the feature for serialization is however currently missing. Only option is using `@JsonProperty` or `toString()` serialization.

**Describe the solution you'd like**
I would like to have `SerializationFeature.WRITE_ENUM_LOWERCASED`.

**Usage example**
Any API endpoint.

### PR DESCRIPTION
**Pull request by knyttl**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Apologies for letting this one fall through the cracks: I think it's a good PR.

I am +1 for adding configurability, but not through existing `SerializationFeature`, only because its capacity is limited and the idea is to keep that for more general settings. Up until now, however, there hasn't been any good alternative.
But Jackson 2.14 will finally implement this:

https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-7

and I will try to collect ideas for `EnumFeature` options: this one sounds like a very good candidate.
To support this, there's some work to be done, similar to how #3421 added `JsonNodeFeature`: @knyttl if you are still interested, I could help make this happen. Or if you don't have time I can maybe implement this on my own when I get some more time.

**Comment by knyttl** [comment]
I am afraid I am not entirely sure about the way this should be implemented so if you want to implement it differently I guess, you better do it yourself 🙏

**Comment by JooHyukKim** [comment]
I recently worked on EnumSerialization a little bit. ✌️
I will try to make a PR if I have time

**Comment by cowtowncoder** [comment]
> I recently worked on EnumSerialization a little bit. ✌️ I will try to make a PR if I have time

Yes, that'd be great! I didn't have time to do this but think it would be quite doable.

**Comment by JooHyukKim** [comment]
> > I recently worked on EnumSerialization a little bit. ✌️ I will try to make a PR if I have time
> 
> Yes, that'd be great! I didn't have time to do this but think it would be quite doable.

For sure! done in #3776

**Pull request closed without merging**
