### PR TITLE
Fix several LGTM findings

### PR DESCRIPTION
**Pull request by artem-smotrakov**
I've had a look at findings and LGTM.

https://lgtm.com/projects/g/FasterXML/jackson-databind/alerts/?mode=tree

None of them look severe to me. Anyway, I tried to fix some of them, and suppressed false-positives by adding comments for LGTM

https://lgtm.com/help/lgtm/alert-suppression

I am not sure I understand how error handling should be done -- I just tried my best. Please let me know if anything needs to be updated. Or, just feel free to drop this pull request if it is complete crap :)

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@artem-smotrakov Thank you for submitting this! Some of these are fine as-is, but some I would prefer not to add (false positives)... not sure what'd be the easiest way. I guess I can manually pick and choose.

If you could add comment-only ones as a separate PR, that'd be helpful I think? It'd reduce number of code changes.

**Comment by artem-smotrakov** [comment]
> If you could add comment-only ones as a separate PR, that'd be helpful I think? It'd reduce number of code changes.

No problem. I'll move the suppression to a separate PR.

**Comment by artem-smotrakov** [comment]
I've moved the suppression to https://github.com/FasterXML/jackson-databind/pull/3203 Feel free to drop it in case you think it is useless.

**Comment by cowtowncoder** [comment]
Looks good -- will merge manually (there will be some conflict b/w 2.13 / master), evaluating as I go, apply most, some with minor tweaks.

Thanks!

**Comment by cowtowncoder** [comment]
Merged most; will wait for LGTM to catch up to see what if anything to do with couple remaining cases (plus whether it's smart enough to follow `Objects.requireNonNull()`)

**Comment by cowtowncoder** [comment]
Most if not all addressed separately, so closing.

**Pull request closed without merging**
