### PR TITLE
enable java 21 testing

### PR DESCRIPTION
**Pull request by pjfanning**
* also allow one extra test class to run with java 11 build

### CODE REVIEW

**Comment by pjfanning** [comment]
Looks like there is a release delay on Temurin side. https://adoptium.net/en-GB/blog/2023/09/temurin21-delay/

**Comment by cowtowncoder** [comment]
Ok, just let me know when this gets ready.

I am bit on a fence as to whether it really makes sense to have separate JDK 11 test set up at all, vs. 8, 17, 21. So maybe instead things should be refactored to align with these.

**Comment by pjfanning** [comment]
> I am bit on a fence as to whether it really makes sense to have separate JDK 11 test set up at all, vs. 8, 17, 21. So maybe instead things should be refactored to align with these.

@cowtowncoder how about getting rid of the jdk14 profile and splitting its test among the jdk11 and jdk17 profiles as my latest commit does?
* jdk14 is not LTS so we probably shouldn't care about it
* jdk11 is LTS and it is useful to run some extra tests when testing with jdk11 (as I am doing here by moving some jdk14 tests to the jdk11 profile)

**Comment by cowtowncoder** [comment]
@pjfanning Yes, we don't need JDK 14 profile for reasons you state. So once JDK 21 is available we can proceed. Or split refactoring into separate PR first. Just LMK when something is ready for merge.

**Review by cowtowncoder — APPROVED** [review]

**Comment by pjfanning** [comment]
One of the tests fails in Java 21. I'll have a look.

```
Error:  Failures: 
Error:    CollectionFormatShapeTest.testListAsObjectRoundtrip:52 expected:<...2,"values":["a","b"][]}> but was:<...2,"values":["a","b"][,"first":"a","last":"b"]}>
Error:  Errors: 
Error:    AccessFixTest.testCauseOfThrowableIgnoral:31 » UnsupportedOperation The Security Manager is deprecated and will be removed in a future release
```

**Comment by pjfanning** [comment]
@cowtowncoder we can probably close this. I think you have the main bits merged to 2.16 branch already and we probably don't want to enable the CI runs for jdk21 yet due to the 2 broken tests.

**Comment by cowtowncoder** [comment]
@pjfanning Either way is fine -- I'll let you leave open or close?

**Comment by JooHyukKim** [comment]
Ahhhh, I see what the problem is now 😅. `ArrayList` in JDK 21 support new method `getFirst()` and `getLast()`. Sorry for photo dump, couldn't find source that can easily show the `@since 21` part.

image

**Comment by cowtowncoder** [comment]
Fixed the first problem, "List as POJO".

**Comment by cowtowncoder** [comment]
And added work-around for the other one, now hoping CI passes so I can merge this.

**Review by cowtowncoder — APPROVED** [review]

**Comment by JooHyukKim** [comment]
Greate job 👍🏼 @cowtowncoder !

**Pull request merged**
