### PR TITLE
Optimize toArray (#2232)

### PR DESCRIPTION
**Pull request by hc-codersatlas**
replace toArray(new T[size]) with toArray(new T[0]) for better performance

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Do you have a link to article discussing this? I remember seeing something that had this counter-intuitive result, but would like to verify.
To be honest, none of the places are in critical path, so it probably does not matter either way, but unless JVM optimizes away zero-array allocations (if it does, cool! :) ), this will add some garbage generation. But as with performance, these are one-offs, and not per-call (i.e. only during initialization & caching).

**Comment by hc-codersatlas** [comment]
Hi, it's in the linked issue, but for your reference also: https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion thanks!

**Comment by GedMarc** [comment]
Java 7 and up :

image

**Comment by cowtowncoder** [comment]
Ok, ended manually merging since those `attic` entries should just be removed, but changes are in.

Thanks!

**Pull request closed without merging**
