### PR TITLE
Add FieldReference in Jackson ValueNode to improve various json processing (e.g masking) 

### PR DESCRIPTION
**Pull request by niralepatel**
Issue type : Enhancement
Issue : https://github.com/FasterXML/jackson-databind/issues/3696

Use case :-
We are trying to mask the node(s) value(s) that matches a single JsonPath or list of JsonPaths. Please note, this json can be very large and we want to achieve this in the most efficient way without degrading the performce.

{"root":
	{"obj": {
		"key1": "secret", 
		"key2": "pwd2"}
	}
}
For above json, if JSONPath expression is given as "$.root.obj.key1 and I want to mask "secret" and if I have a referce of ObjectNode and field name(key1) for this ValueNode, then I can set maskedValue using getObject().set(fieldName,value) method.

	ValueNode vn= ....
	FieldReference fr = vn.getFieldRef();
	if (fr != null) {
		fr.getObject().set(fr.getFieldName(), maskNode);
	}
If we do not have the reference then, to mask perticular value, we have to traverse the entire json recursively and find out the reference and then set it which can increase the time complexity.

Solution:-
Setting the FieldReference (fieldName and ObjectNode)in ValueNode will help to perform any action on that perticular ValueNode without traversing the entire json.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
First of all: thank you offering this contribution for the project.

Unfortunately, as per my notes on #3696, I don't think this is something we can or want to do.
I realize it is something that'd be useful to you and your use case, but changing current tree structure into actual graph (due to back references) is against a fairly fundamental design constraint.

There is also the question of adding overhead for existing use cases for user who do not need parent linkage.

So, I don't plan to merge this in its current form (nor likely with any changes)

**Comment by pjfanning** [comment]
@cowtowncoder could the idea of subclassing be affected by https://github.com/FasterXML/jackson-databind/pull/3701 ?

**Comment by cowtowncoder** [comment]
> @cowtowncoder could the idea of subclassing be affected by #3701 ?

Correct, that fix would probably be pre-requisite for things working as expected.

So clearly not many developers have tried using custom subtypes as this was only recently reported. But then again, author of that fix might be able to help wrt sub-classing and sharing their experiences.

**Comment by cowtowncoder** [comment]
Not planning to get this merged as per my earlier notes; closing as part of PR clean up.

**Pull request closed without merging**
