### PR TITLE
Follow ups from FasterXML/jackson-databind#838

### PR DESCRIPTION
**Pull request by zoliszel**
As per #838

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thanks!

**Comment by zoliszel** [comment]
Thank you!

**Comment by zoliszel** [comment]
Hi,

when do you think a release be available with these changes in?

Regards,
Zoltan

**Comment by cowtowncoder** [comment]
Trying hard to finalize 2.6.0, so within 2 weeks I think.

**Comment by zoliszel** [comment]
Cool, will watch out for it.

Thank you,
Zoltan

On 9 July 2015 at 20:40, Tatu Saloranta <notifications@github.com> wrote:

> Trying hard to finalize 2.6.0, so within 2 weeks I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-databind/pull/855#issuecomment-120100360>
> .
>

-- 


------------------------------

*IMPORTANT NOTICE*: MahiFX Limited (*MahiFX*), (company no. 2446590) is 
registered in New Zealand. MahiFX is authorised and regulated by the 
Australian Securities and Investment Commission ARBN 152 535 085, AFSL 
414198. This email, its attachments and any rights attaching hereto are 
confidential and intended exclusively for the person to whom the email is 
addressed. If you are not the intended recipient, do not read, copy, 
disclose or use the contents in any way. Please notify the sender by return 
email and destroy the email and attachments immediately. MahiFX does not 
accept any liability for any changes made to this email or attachments 
after sending by MahiFX. You must scan this email and attachments for 
viruses. The opinions expressed are not necessarily those of MahiFX. MahiFX 
accepts no liability for any loss, damage or consequence, whether caused by 
our own negligence or not, resulting directly or indirectly from the use of 
this email and attachments.

For more information about MahiFX Limited see mahifx.com.

**Pull request merged**
