### PR TITLE
Add test for #4388

### PR DESCRIPTION
**Pull request by JooHyukKim**
Add tests to prove that #4388 is already resolved, since 2.17 or earlier.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks like ordering of `products` does not vary, I'll see if I can change that.

**Comment by cowtowncoder** [comment]
@JooHyukKim I made a change to show (I think) that:

1. Unwrapped properties are sorted as expected, but
2. Any-properties are always serialized after everything else

if so, we could split #4388 into two: one for unwrapped (which appears to work), and separate one for Any-properties (which does not).

**Comment by JooHyukKim** [comment]
> Looks like ordering of `products` does not vary, I'll see if I can change that.

Good call! Thanks, I totally missed that.

> if so, we could split #4388 into two: one for unwrapped (which appears to work), and separate one for Any-properties (which does not).

Right.

**Comment by JooHyukKim** [comment]
Should we close this in favor of #4396? @cowtowncoder

**Comment by cowtowncoder** [comment]
@JooHyukKim was about to ask about it. I think that makes sense.

**Pull request closed without merging**
