### PR TITLE
support nested TypeDeserializer

### PR DESCRIPTION
**Pull request by devefx**
support nested TypeDeserializer

### Example

```java
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "post_type", visible = true)
@JsonSubTypes(value = {
        @JsonSubTypes.Type(name = "message", value = MessageEvent.class),
        @JsonSubTypes.Type(name = "notice", value = NoticeEvent.class)
})
@Data
public abstract class Event {
   String post_type;
   // some filed
}


@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "message_type", visible = true)
@JsonSubTypes(value = {
        @JsonSubTypes.Type(name = "private", value = PrivateMessageEvent.class),
        @JsonSubTypes.Type(name = "group", value = GroupMessageEvent.class)
})
public abstract class MessageEvent extends Event {
   String message_type;
}

@Data
@EqualsAndHashCode(callSuper = true)
public class PrivateMessageEvent extends MessageEvent {
    Object sender;
    // some filed
}

@Data
@EqualsAndHashCode(callSuper = true)
public class GroupMessageEvent extends MessageEvent {
    Long groupId;
    // some filed
}


public abstract class NoticeEvent extends Event {
   // some filed
}

```

### Test passed

```java
@Test
public void privateMessageTest() throws JsonProcessingException {
    String str = "{\"font\":1326744,\"message\":[{\"data\":{\"text\":\"hello\"},\"type\":\"text\"}],\"message_id\":1,\"message_type\":\"private\",\"post_type\":\"message\",\"raw_message\":\"hello\",\"self_id\":123456,\"sender\":{\"age\":1,\"nickname\":\"Yoke\",\"sex\":\"male\",\"user_id\":123456},\"sub_type\":\"other\",\"time\":1577894793,\"user_id\":123456}";

    Event event = objectMapper.readValue(str, Event.class);

    Assert.assertNotNull(event);
    Assert.assertTrue(event instanceof PrivateMessageEvent);
}
```

### CODE REVIEW

**Comment by sigpwned** [comment]
This looks great. I'd use this feature if it were merged. Are there any concerns with this PR? If so, I'm happy to help you resolve, @devefx!

**Comment by cowtowncoder** [comment]
I think that last I looked into this I was not quite comfortable the way I think it works -- first it was not clear how it would work, and even when I think I figured it out it seemed like a wrong way to resolve things, happening to work specific case but (from what I think) unlikely to cover cases where contextualization (access to annotations of a property for which deserializer is created) is needed.

More fundamentally, to make multi-level resolution work, nested deserializers seem necessary, leading to multiple levels of buffering of content. I am not sure I actually want this to be supported.

So, unfortunately at this point I am not confident this should be merged at all, and would need to understand the logic better. I realize that without having tests that prove that problems exist (which I think do) it is difficult to proceed here, but... I am not sure if to proceed, even.
To me it seems that to support nested type resolution, a small targeted patch will not work and instead major rewrite would be needed. One would actually be needed for a few other things (like "type id - less polymorphism" [such as inferring type from existence / lack thereof of values]), but unfortunately I have not had time to progress that at all. And it is unlikely I will have time any time soon, given that I only work on my spare time with Jackson.
But major changes, if  they were made, would (need to) go in Jackson 3.0, not 2.x.

**Comment by sigpwned** [comment]
Really appreciate the response, @cowtowncoder. I understand, and appreciate your work very much. Thank you for taking typing out the detailed explanation!

**Comment by cowtowncoder** [comment]
@sigpwned no problem. I feel bad for not being able to resolve this issue at this point, but I will keep it in mind as one of open issues nonetheless. Sometimes new approaches (or re-evaluation of existing ones) leads to solutions at a later point; never say never.

**Comment by cowtowncoder** [comment]
No plans to proceed with this one, closing.

**Pull request closed without merging**
