### PR TITLE
Add GitHub workflow to replace Travis CI

### PR DESCRIPTION
**Pull request by joschi**
Replace the Travis CI build job with an equivalent GitHub workflow and add wrapper for Maven 3.6.3.

**TODO:** Add `CI_DEPLOY_USERNAME` and `CI_DEPLOY_PASSWORD` encrypted secrets to repository:
https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

### CODE REVIEW

**Comment by joschi** [comment]
GitHub Actions currently doesn't support non-x86 machine architectures out of the box, so this might be something to consider before migrating.

There's still the option to provider self-hosted runners with that machine architecture:
https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/

**Comment by cowtowncoder** [comment]
Thank you for contribution! I think this will need to be discussed on mailing lists; and since I plan to take bit of a break over december, it may take a while to figure out how to proceed. But it is good to know we have options.

**Comment by cowtowncoder** [comment]
Ok. With the latest breakage of Travis-CI builds, I hope to have time to revisit this: I like the idea of the move more now. :)
Just need to clear up backlog of other issues first.

**Comment by cowtowncoder** [comment]
@joschi Quick request: could you split this into 2 PRs by cleaving out change to use `mvnw` wrapper, to be merged in 2.13 (seems like a good idea in general), and leaving this one for Github actions?

I guess this should also go against 2.13 branch; although not sure how branches work wrt Github actions? (I changed default branch to be 2.13 since this PR was created, as most users really need the latest 2.x, not `master`).

**Comment by joschi** [comment]
I've updated the PR accordingly.

Example run (which ultimately failed due to the missing credentials for Sonatype OSS):
https://github.com/joschi/jackson-databind/actions/runs/966923385

**Comment by cowtowncoder** [comment]
Cool @joschi! So if I was to create Org-wide secrets with appropriate name, this could actually work?

Extending on that: locally I use username/password pair for OSSRH Nexus, but I was thinking that there should probably be a way to generate access token(s) that could be used as well? If so, that'd be nice, even if it still used my personal access rights, but would be bit easier to revoke.

**Comment by cowtowncoder** [comment]
@joschi Hmmh. Ok, so adding 2.13 as allowed branch enabled builds, but despite my adding secrets the way I thought they might work, snapshot publish fails. I'll see that secrets are available... but hard to know what is wrong since as usual for security reasons amount of information is limited.

I noticed that snapshot deploy only occurs for pushes which is good (wouldn't want PRs to trigger them).

But I wonder if there's attempts to push for both JDKs (8 and 11)? If so, would it be possible to make that only happen for JDK 8?
(I'll check logs to make sure I'm not mistaken).

**Comment by cowtowncoder** [comment]
LOL/Doh! I had forgotten to Save selection of repositories that should have access to password secret. I bet that would help.... :)

**Comment by cowtowncoder** [comment]
Ok, yes, so deploy runs for both variants; need to figure out either how to prevent it or, perhaps, create separate jobs (or workflows?) for "Build+Verify" (over full matrix, run tests, no deploy" vs "Deploy Snapshot" (only for one JDK (8 for now); no tests, deploy snapshot).

**Comment by joschi** [comment]
@cowtowncoder I've seen that you've already added the necessary condition to only publish builds with Java 8 in c23e271f14ce48325c00fc18ff10ba8cc90113ed. 👍 

Let me know if you have more questions or ideas how to improve the workflow.

**Comment by cowtowncoder** [comment]
Sounds good -- thank you for providing the patch @joschi!

**Pull request merged**
