### PR TITLE
Fix for #3025

### PR DESCRIPTION
**Pull request by Migwel**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Makes sense, thank you @Migwel!

One thing I'll have to ask you before merging -- if I have not done that before (I think I haven't but I may have missed an email) is to get CLA for the contribution. This is only needed once and works for all future contributions. Document is at:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual way is to print it, fill & sign, scan (photo is fine), email to `info` at fasterxml dot com.
Once I received it I'll file and can merge this PR (as well as any others related or unrelated for Jackson projects).

Looking forward to fixing the issue -- this is a nasty problem, thank you for reporting it & contributing the fix!

**Comment by Migwel** [comment]
@cowtowncoder I've done that a few months ago already when I contributed so you should have it already. Happy to do it again if needed

**Comment by cowtowncoder** [comment]
@Migwel no that's fine, I probably wasn't searching with right word in my gmail -- let me re-check. I do remember contribution.

**Comment by cowtowncoder** [comment]
@Migwel my bad -- I can see the CLA now (was just the "w" vs "u" in email address). No need to send anything, I'm good :)

**Pull request merged**
