### PR TITLE
New feature: @JsonIgnoreIf

### PR DESCRIPTION
**Pull request by sebastianbrunnert**
Hello everyone,

In several projects (especially REST APIs) in which I used Jackson I needed the feature to ignore an Jackson property dynamically (e.g. based on authorization). I always used some kind of workaround.

So I decided to build the @JsonIgnoreIf annotation. You can specify a class extending the abstract class JsonIgnoreValidator.
The usage is basically very easy.

```java
public static class JsonIgnoreForGuests extends JsonIgnoreValidator {
    @Override
    public boolean ignore() {
        // Example with Spring: Ignoring if there is no Authentication
        return !SecurityContextHolder.getContext().getAuthentication().isAuthenticated();
    }
}
```

Defining properties that should be checked before transfering into JSON works by:

```java
@JsonIgnoreIf(JsonIgnoreForGuests.class)
public String sensibleData = "Lorem Ipsum";
```

Excuse me for possible formal mistakes. This is my first open-source contribution ever.

Best regards from Germany
Sebastian

### CODE REVIEW

**Comment by yawkat** [comment]
Have you considered using views instead?

https://www.baeldung.com/jackson-json-view-annotation

**Comment by sebastianbrunnert** [comment]
Yes, of course.
But it can be a mess when handling with a more detailed authorization or other use cases.

**Comment by cowtowncoder** [comment]
@sebastianbrunnert First of all: thank you for contributing this feature.

I will have to think about this really hard. On one hand, implementation is delightfully simple, and I can see how this could be very useful.

On the other hand, I'll have to think about API, extensibility and so on. The way `AnnotationIntrospector` works is that usually there'd be an accessor method of some kind to allow overrides and so on.
Ideally method might be given some more contextual information, to allow for more generic implementation (not having to implement validator for every distinct field).

But first things first: I think you'd want this to be based against `2.14` branch, not `master` -- latter is for Jackson 3.0 which will still take a while to be finalized.

Second thing I'll have to think about is the annotation itself. Traditionally it'd go in `jackson-annotations`. Although in this case maybe it belongs to `jackson-databind` annotations. So no need to change yet.

Third thing would be CLA but that's taken care of (received it, thanks!).

So... really the only immediate thing I'd need is just rebase against `2.14`.

**Comment by sebastianbrunnert** [comment]
@cowtowncoder Thanks for your feedback!
As I said I have no huge Open-Source experience. Does that mean I have to make a completly new Pull Request or commit my changes to the 2.14 branch?

**Comment by yawkat** [comment]
@sebastianbrunnert you can do a git rebase onto the 2.14 branch, force push it to your pull request branch, and then change this PR to target the 2.14 branch in the github UI.

3.0 and 2.x have some API differences, so you may need to do code changes, I'm not sure.

**Comment by sebastianbrunnert** [comment]
Let me create a new PR :D

**Pull request closed without merging**
