### PR TITLE
#1601

### PR DESCRIPTION
**Pull request by cfogrady**
Null Polymorphic Deserialization fails.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
First of all: thank you for submitting this.

As per my comments on issue itself, 2.4 branch has been closed for quite a while now, so I won't be merging fixes there. But I would be interested in knowing if problem still persists in open branches (2.7, 2.8, master). So would it be possible to verify against `2.7` branch? (latest release is 2.7.9).

If so I can have a look: fix seems like possibility, but typically deserializers should not have to deal with null tokens as they are handled by caller. So it would seem like a check might be missing upstream, that is, caller should be handling it. I can help with that part, with unit test provided.

**Comment by cfogrady** [comment]
Hi. It is not reproducible in later versions thankfully. Currently my company is stuck on 2.4 because of other dependencies. We are looking to upgrade, but have not been able to do so yet, hence my patch.

**Comment by cowtowncoder** [comment]
@cfogrady Ok. The problem is, as I said, that 2.4 is closed in that no more releases are planned to be made there. So while I could just merge this it is not clear whether it would be useful for you (for example).

Then again it'd be possible to do merge, release `2.4.6.2` of just `jackson-databind` no full release of all components). 
If this is a critical problem for you I could consider doing that.

Or you could use a local build / fork.

**Comment by cfogrady** [comment]
@cowtowncoder 
Not really a problem. I got around it by using my fork until we can upgrade. I just thought that it could benefit any other individuals who were stuck on 2.4 because of other dependencies.

**Comment by cowtowncoder** [comment]
@cfogrady Ok. Challenge on our end is just the significant overhead if trying to maintain many older branches (current `master` is for 2.9.0), so need to limit that work.

I will actually merge this PR since as you say perhaps others find it useful as well.

**Pull request merged**
