### PR TITLE
Fix issue 944: fix up logic for custom key deserializers for enums.

### PR DESCRIPTION
**Pull request by bimargulies**
This fixes issue 944: problems with custom key deserializers.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ok sounds good. One question: this is against master, which would be for 2.7.0-SNAPSHOT. What is the easiest way to merge it back to 2.6 branch, if I merge this?

**Comment by cowtowncoder** [comment]
Or, conversely, would it be possible to redo PR for 2.6 branch.

**Comment by bimargulies** [comment]
I built it against 2.6 and then made the PR wrong. I can fix it later or
you can use git cherry-pick.

**Comment by bimargulies** [comment]
I can remake the PR in a few hours.

**Comment by cowtowncoder** [comment]
That's ok, I can try my luck with cherry-pick I think :)

**Pull request merged**
