### PR TITLE
Deserialize integer/long JSON into double single-arg constructors

### PR DESCRIPTION
**Pull request by davidmoten**
As discussed in #4453 

This PR ensures that deserialization of integer/long json like `5` or `12345678901` occurs without error when the target class has a single argument constructor of argument type `double`. This ensures consistency with the treatment by Jackson of deserialization into multi-arg constructors (annotated with `@JsonProperty`).

Tests provided give full coverage of changed code and I've also tested that expected preferences are applied when multiple constructors are available.

Note that other types (like `float` at least) will be handled in another PR.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you! I hope to review this soon, get it merged.

ONe process thing: if we haven't yet gotten a CLA (only needs to be done once so if there is one, that's good), we'd need one from:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual way is to print it, fill & sign, scan/photo, email to `cla` at fasterxml dot com.
Once it's done I can proceed with merge & cla is good for any and all future contributions.

**Comment by davidmoten** [comment]
contributor agreement has been sent

**Comment by cowtowncoder** [comment]
CLA received, hoping to merge tomorrow. Thank you for sending CLA so quickly!

**Review by cowtowncoder — APPROVED** [review]
LGTM

**Comment by cowtowncoder** [comment]
Ok looks good but will need to wait until tomorrow to merge (ran out of time tonight, wrt merge to `master`/3.0).

**Review by cowtowncoder — APPROVED** [review]

**Pull request merged**
