### PR TITLE
Case-insensitive boolean deserialization

### PR DESCRIPTION
**Pull request by remal**
It's a fix for #1852

### CODE REVIEW

**Comment by cowtowncoder** [comment]
First of all, thank you for PR!

Now, as per my notes I think what is needed is support for using either "leniency" (via `@JsonFormat.lenient`), or case-sensitivity. Actually probably latter.
So I am not sure whether to apply this at this point.
Problem here is that there are users who want stricter handling (as well as others who want more flexible one, of course :) ), and I would like to have controls in place to allow both, before extending definition.

**Comment by remal** [comment]
@cowtowncoder I believe I saw a special Jackson setting that switches from strict/not strict. Let me do a little research on Monday...

**Comment by cowtowncoder** [comment]
So: since 2.10 adds more specific `JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_VALUES` / `MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES`, I think that is what needs to be used here.
Will close this PR.

**Comment by oghanek** [comment]
I tried using the new Features in my code but it does not help me against uppercased value like "TRUE"
My code
`mapper.configure(MapperFeature.USE_STD_BEAN_NAMING, true)
            .configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES, true)
            .configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
            .configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, false)
            .configure(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES, true)
            .configure(SerializationFeature.FAIL_ON_SELF_REFERENCES, true)
            .setSerializationInclusion(JsonInclude.Include.NON_EMPTY);`

**Pull request closed without merging**
