### PR TITLE
Deserialize time-only XMLGregorianCalendar

### PR DESCRIPTION
**Pull request by rgoldberg**
If `StdDeserializer#_parseDate(JsonParser DeserializationContext)` throws `InvalidFormatException` when parsing an `XMLGregorianCalendar` using the Jackson date format, fallback to parsing using the XML Schema date / datetime / time / etc. lexical representation.

This adds support for time-only `XMLGregorianCalendar`.

This is an implementation for #1165.

Can this be backported to 2.7.4, and also included in 2.8.0?

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for your help here.

I am not quite sure what the nested handling here is meant to achieve. From comments it would seem like it would be to support "accept single value as array" feature; but this is not responsibility of value deserializers; it is something array/Collection deserializers take care of. So I think that does not belong here.

Other than this code does a fallback, which probably makes sense.

**Comment by rgoldberg** [comment]
I would normally agree that "accept single value as array" shouldn't be implemented here.

But, "accept single value as array" is implemented in `StdDeserializer#_parseDate(...)` in the recursive code after the comment `// Issue#381`.

`_parseDate(...)` is called from the existing `CoreXMLDeserializers.Std#deserialize(...)`, so I thought that I might need to handle this same situation in my new code.

e.g., if `_parseDate(...)` throws an `InvalidFormatException` in the middle of the recursion once it has found the first non-array descendant, then the depth of the array nesting will be lost because the recursion will have ended, but the `JsonParser` will already have been advanced to the first non-array descendant.  When I catch the exception in my new `CoreXMLDeserializers.Std#parseXMLGregorianCalendarNotNested(...)`, and then try to fallback to calling `_dataTypeFactory.newXMLGregorianCalendar(String)`, I won't know how deep the value was, so I won't be able to unwind the `JsonParser` to the correct depth of nested arrays, nor verify that none of those nested arrays contain any other elements, in which case I should throw a `JsonMappingException`, just like `_parseDate(...)` does.

So, I need to get the depth before I call `_parseDate(...)`, so that I have the depth as an int to use in the fallback block.

I should only remove the iterative nested array handling if one of the following is correct:

1. the recursive nested array handling should also be removed from `_parseDate(...)`
2. the recursive nested array handling should be left in `_parseDate(...)`, but it turns out that whenever `CoreXMLDeserializers.Std#deserialize(...)` is called, the nested arrays have already been processed, and therefore `_parseDate(...)` will never recurse in this situation (it's just that `_parseDate(...)` might be called from other methods, so it needs the recursive handling for these other circumstances, but not for `deserialize(...)`).

Does what I'm saying make sense?

**Comment by rgoldberg** [comment]
While this is pending merge and official release, I need to use a modified version of jackson-databind 2.7.3 from a private Sonatype Nexus Repo maven server.

I don't really know maven directly (I've used other build tools that publish to maven).

I'm able to generate & deploy the binary jar, but I'm not sure how to generate corresponding source & javadoc jars, and how to deploy those to Nexus.

To build & deploy the binary jar, I successfully run the following from the root of my modified jackson-databind clone:

    mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/jackson-databind-2.7.3.jar -DrepositoryId=example.com -Durl=http://example.com:8081/repository/maven-releases/

How should I modify that (or what should I run beforehand) to generate & deploy the source & javadoc jars?

Any help would be appreciated.

Thanks.

Sorry to ask this here, but it would help me out a lot if you know how to do this.

**Comment by cowtowncoder** [comment]
Oh. Yes you are absolutely right -- I had forgotten that there is such handling sprinkled around in a few places.
What threw me off was the handling of variable number of nested scopes; and even that does work. Note, however, that such nesting is not supported elsewhere, so it's probably not worth implementing here either (I understand that it's technically not that much more complicated to do... but still, single level is all that works elsewhere).

With that, it makes bit more sense. I'll try to go over code again tomorrow.

**Comment by rgoldberg** [comment]
I would imagine that the best way to universally handle nested single-element arrays would be to refactor the Jackson code to use my iterative nesting handling before `deserialize(...)` is called, and my iterative un-nesting after `deserialize(...)` is called.  I wanted to limit the scope of my changes, however, so I just embedded it in the `XMLGregorianCalendar` deserialization code to support everything that the old version did.

Thanks for looking over this.

**Comment by cowtowncoder** [comment]
@rgoldberg Yeah the whole nesting/unnesting is an unfortunate detour.

**Comment by rgoldberg** [comment]
Do I need to change anything?

**Comment by cowtowncoder** [comment]
@rgoldberg no I think you are good. Next (and last I hope) question: have I asked for a CLA yet?

It's found from https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf and typically you print, fill & sign, scan and email to `info` at fasterxml dot com. We need this from all contributors, but just once before first commit. If you could do this, I can merge the patch and make any minor tweaks I'd like.

**Comment by rgoldberg** [comment]
Just emailed the signed CLA.

**Comment by cowtowncoder** [comment]
Hmmh. I wish there was a unit test here... I will rewrite this patch slightly, but would prefer not breaking additional processing. I just realized that the base class already takes care of unwrapping, so there should not be need to handle it here.

**Pull request merged**
