### PR TITLE
Fix wording.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
I think that'd be wrong: serialization being writing JSON out, and matching is indeed done on deserialization?

**Comment by johnjohndoe** [comment]
One of the two must be wrong - the [opposite operation](https://github.com/johnjohndoe/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/MapperFeature.java#L272) is described in the next paragraph: 

> ... determines if Enum deserialization should ...

**Comment by cowtowncoder** [comment]
No, they just apply to different things: first one for POJO property names, second one for Enum values.
I'm sure wording could be improved but both of these apply to deserialization.
(and reason why they are not in `DeserializationFeature` is technical, not semantic one: these settings can not be changed dynamically but must be configured for `ObjectMapper`, can not be changed for `ObjectReader`)

**Comment by johnjohndoe** [comment]
Okay then - thank you for the clarification. :smile_cat:

**Pull request closed without merging**
