### PR TITLE
Added FAIL_ON_EXTERNAL_TYPE_ID_MISSING_PROPERTY deser property

### PR DESCRIPTION
**Pull request by ckuhn**
This property controls the behavior of deserializing subtype properties
that use the EXTERNAL_PROPERTY type id.

### CODE REVIEW

**Comment by ckuhn** [comment]
If this shouldn't be configurable with a DeserializationProperty, let me know and I will fix it so that it only throws the exception in case of a required property.

**Comment by cowtowncoder** [comment]
Do you have a separate issue for PR to explain why this is needed, thinking behind needing the feature?

**Comment by ckuhn** [comment]
The issue is that when the subtype property is missing, an exception is thrown. I had some legacy input to take that sometimes included the suptype property and sometimes didn't. I couldn't figure out any other way to fix the issue besides adding a feature, or simply not throwing the exception.

Is there another way around this issue?

Quick example:

No issue with this
```json
{
   "type": "orange",
   "fruit": {
      "name" : "Mandarin"
   }
}
```

Exception thrown, when 'fruit' property could just be null.
```json
{
   "type": "orange"
}
```

**Comment by cowtowncoder** [comment]
Ok, so this would be for cases where "type id" itself is specified, but no actual payload (data)?
That sounds legit to me. The only question is whether feature name is optimal to give the idea of its working (that is, is there an even better name to use :) ).

Thank you for explaining the intent.

**Comment by cowtowncoder** [comment]
Before merging the patch, the only process thing we need is to get a filled Contributor License Agreement from:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

(unless I have asked for one before?)

The usual method is to download, print, fill + sign & scan it, and email to `info` at fasterxml dot com.
With that I can proceed with merge, plus CLA is good for any other contributions for Jackson projects as well.

Thank you for submitting this PR!

**Comment by ckuhn** [comment]
I can change the feature name if needed. Any suggestions?

**Comment by cowtowncoder** [comment]
Thanks, I can merge, consider the change.

One problem wrt 2.8 is that I think the default must be `true`, actually, to avoid any behavioral change, and switch default in 2.9.
Or wait for 2.9 to add this in, with `false` straight away.
Given that if merged for 2.8 it will be "hidden" feature (documented only for 2.9 as new functionality ought to be added in minor versions, not patches), approaches are quite similar; so I think what I'll do is just to merge in and make default `true`.

I noticed the CLA, so I can proceed with merging soon, hopefully tomorrow. Thanks again!

**Comment by cowtowncoder** [comment]
Renamed feature as `FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY`.

**Pull request merged**
