### PR TITLE
fix a flaky test 

### PR DESCRIPTION
**Pull request by arianacai1997**
In `testUnwrapping`, the order of the `properties` is not fixed. Therefore, I added all the possibilities to the code.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for suggested improvement! In this case extra code is a bit too much so instead of adding more hard-coded Strings, I think solution needs to be to parse the result (as `JsonNode` for example) and verify contents that way.
That is bit more work but more maintainable.

**Comment by arianacai1997** [comment]
> Thank you for suggested improvement! In this case extra code is a bit too much so instead of adding more hard-coded Strings, I think solution needs to be to parse the result (as `JsonNode` for example) and verify contents that way. That is bit more work but more maintainable.

Thank you for the suggestion! I will modify the code accordingly.

**Comment by arianacai1997** [comment]
> Thank you for suggested improvement! In this case extra code is a bit too much so instead of adding more hard-coded Strings, I think solution needs to be to parse the result (as `JsonNode` for example) and verify contents that way. That is bit more work but more maintainable.

Please take a look and see if the latest modification works better. Thanks!

**Comment by cowtowncoder** [comment]
Thanks!

**Pull request merged**
