### PR TITLE
 WMCloud-0# Changes in Bean serializer to handle cicular loop in jackson...

### PR DESCRIPTION
**Pull request by DeepikaChary**
... serialization.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
You may not have realized this, but serializers are shared, so instances can not have any state.
So I don't think this would work with typical concurrent use.

But what exactly is the problem being solved here?

**Comment by jvenugopal** [comment]
I agree with cowtowncoder that the state should not be maintained in the Serializers. I think, it should be moved to SerializationProvider. (correct me, if I'm wrong).

Problem statement:
We are trying to solve the cycling dependency problem during serialization. Say for example, if there is an object hierarchy in which A has a reference to B, B to C, C to D and D to B ( A -> B-> C-> D -> B), then when we serialize an object of A, it should serialize A, B, C & D, but stop at B while serializing D instead of going into cyclic loop. 

Currently we have not find a way in FasterXML to do the same. The current patch maintains the Stack of objects being serialized during the serialization process. It breaks the serialization if it finds the object which is already there in the stack.

**Comment by cowtowncoder** [comment]
And you can not use `@JsonIdentityInfo` for serializing second case of `B` with Object Id? This would be the standard way of handling with cyclic data structures.

I agree in that `SerializerProvider` is the place that can have state, and if you can modify that it should work. I do not think I want core databind to store such stack since it will add measurable amount of overhead (simply just keeping the stack, not to mention checking for object existence); but I am open to changes that allow custom code to do that.

**Comment by jvenugopal** [comment]
Yes, `@JsonIdentityInfo` is what we initially tried. But `@JsonIdentityInfo` replaces all occurrences of the previously visited objects with the Object Id,  irrespective of whether they are visited in the current serialization stack or not. 

This introduces couple of issues with the generated output:
* The json output of the serialization is not uniformly constructed even for a list of homogeneous objects.

          Say for example I have a class A as shown below:  
         @JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@id")
         public class A {
             public String value;
             public A next;
         }

        //create an instance of A  
        A a = new A();
        a.value = "first";

        //create another instance and set the next of value to it previous instance.
        A b = new A();
        b.value =  "second";
        b.next = a;

        //add second instance first and first instance next to the list.
        List<A> list1 = new ArrayList();
        list1.add(b);
        list1.add(a);

        //then use ObjectMapper to serialize the list object.
        Then the actual output is:
        [{"@id":1,"value":"second","next":{"@id":2,"value":"first","next":null}},2]

        But expected output is:
        [{"@id":1,"value":"second","next":{"@id":2,"value":"first","next":null}},{"@id":1,"value":"first","next":null}]

* It requires additional processing at the client side before using the data.

I would like to see `@JsonIdentityInfo` consider the current stack for finding whether an object is visited or not, instead of looking across all the visited object in the complete serialization process. If so, this patch is not required. In either way the stack needs to be maintained and used for object existence.

**Comment by cowtowncoder** [comment]
Interesting. Although I have not had the need for such handling for my own use, I can see how it could be useful. I don't think behavior of `@JsonIdentityInfo` as default should be changed, since its semantics are quite clear and existing use cases rely on current behavior. But perhaps it could be possible to offer alternative ways of dealing with id handling.

That said, you may be able to override functionality used for Object Id, and implement alternative stack-based strategy, since life-cycle of object id references could work well for your purposes.

**Comment by cowtowncoder** [comment]
I don't think I want to merge this patch in as-is, since adds non-trivial overhead for checking for cyclic dependencies. I am open to adding options to tackle this problem, if they can be done in a way that does not add measurable overhead for the common case of not checking for cycles (possibly enabled via `DeserializationFeature` or maybe `MapperFeature`).
There are some other possibly issues here (for example, serializer actually must output a value, it is not legal to simply omit it in case of property values), but those would be addressable.

**Pull request closed without merging**
