### PR TITLE
Try to make code android 6 (SDK 23) compatible

### PR DESCRIPTION
**Pull request by shanjunmei**
Its implementation is very simple and we can foresee that it will not cause any side effects

### CODE REVIEW

**Comment by iProdigy** [comment]
the try-catch approach is likely overkill (see original fix commit https://github.com/FasterXML/jackson-databind/commit/0ede93508cdf4c66791fbe436fc1e917a14dae19#diff-e3b0b5408a33e269ed50f7c3a5c222d9c66715351d0ac5bbde1719a5ee50253f)

unfortunately [this merge](https://github.com/FasterXML/jackson-databind/commit/fd2609572b198d8bd5f8da6dcd4dab5417e8f364) reversed that patch (see file at prior commit)

**Comment by shanjunmei** [comment]
> unfortunately [this merge](https://github.com/FasterXML/jackson-databind/commit/fd2609572b198d8bd5f8da6dcd4dab5417e8f364) reversed that patch (see file at prior commit)

before i review jdk source code ,i have same concern ,

`    /**
     * {@inheritDoc}
     */
    @Override
    public Class<?>[] getParameterTypes() {
        return parameterTypes.clone();
    }

    /**
     * {@inheritDoc}
     * @since 1.8
     */
    public int getParameterCount() { return parameterTypes.length; }`  this is copy from jdk source code

**Comment by shanjunmei** [comment]
> > unfortunately [this merge](https://github.com/FasterXML/jackson-databind/commit/fd2609572b198d8bd5f8da6dcd4dab5417e8f364) reversed that patch (see file at prior commit)
> 
> before i review jdk source code ,i have same concern ,
> 
> ` public Class<?>[] getParameterTypes() { return parameterTypes.clone(); } public int getParameterCount() { return parameterTypes.length; }` this is copy from jdk source code

We can find that if we directly replace it with the length of parameterTypes, it will clone parameterTypes .

**Comment by iProdigy** [comment]
another note: `getParameterCount` is also used elsewhere, so this patch alone won't allow lowering the min android sdk version (which is currently [26](https://github.com/FasterXML/jackson-databind/blob/f49a58e44fbfcd83f077ee2ee486181b06cb7491/pom.xml#L49-L50), and even 2.13 didn't support android 6)

**Comment by shanjunmei** [comment]
> another note: `getParameterCount` is also used elsewhere, so this patch alone won't allow lowering the min android sdk version (which is currently [26](https://github.com/FasterXML/jackson-databind/blob/f49a58e44fbfcd83f077ee2ee486181b06cb7491/pom.xml#L49-L50), and even 2.13 didn't support android 6)

For me, this one modification is enough. Of course, if necessary, I will be happy to make similar fixes to all similar codes.

**Comment by iProdigy** [comment]
> Of course, if necessary, I will be happy to make similar fixes to all similar codes.

i don't think the maintainers are interested in that approach: https://github.com/FasterXML/jackson-databind/issues/3702#issuecomment-1358396811

you'll likely have to use a forked version of jackson in your app if you want sdk 23 compatibility

**Comment by shanjunmei** [comment]
> > Of course, if necessary, I will be happy to make similar fixes to all similar codes.
> 
> i don't think the maintainers are interested in that approach: [#3702 (comment)](https://github.com/FasterXML/jackson-databind/issues/3702#issuecomment-1358396811)
> 
> you'll likely have to use a forked version of jackson in your app if you want sdk 23 compatibility

In fact, I have already done this, but I don’t want to miss the new updates of Jaskson in the future. I believe that the original worry was also due to the performance loss caused by clone, but now this problem will no longer exist. hi  @cowtowncoder ,can you help check this approach

**Comment by shanjunmei** [comment]
I understand that we need to keep pace with the times, but sometimes we also have to adapt and understand the reality. Just like Android, it lags behind Java’s feature support, and even the official has come up with a solution to desugar.

**Comment by shanjunmei** [comment]
> another note: `getParameterCount` is also used elsewhere, so this patch alone won't allow lowering the min android sdk version (which is currently [26](https://github.com/FasterXML/jackson-databind/blob/f49a58e44fbfcd83f077ee2ee486181b06cb7491/pom.xml#L49-L50), and even 2.13 didn't support android 6)

btw, I have done the same for all getParameterCount calls based on 2.1.7

**Comment by cowtowncoder** [comment]
No, not going go back -- we have gone down this path multiple times.

We do have Animal Sniffer check for Android SDK compatibility and baseline we have (26 I think) and absolutely no plans to try to reduce it.

So this will not be accepted.

**Comment by shanjunmei** [comment]
> No, not going go back -- we have gone down this path multiple times.
> 
> We do have Animal Sniffer check for Android SDK compatibility and baseline we have (26 I think) and absolutely no plans to try to reduce it.
> 
> So this will not be accepted.

As you said, this situation has happened many times. Doesn’t this mean that there is something wrong with the current approach?

**Pull request closed without merging**
