### PR TITLE
add APPLY_DEFAULT_VALUES DeserializationFeature

### PR DESCRIPTION
**Pull request by pjfanning**
@cowtowncoder relates to https://github.com/FasterXML/jackson-module-scala/issues/514 - feel free to suggest changes

### CODE REVIEW

**Comment by cowtowncoder** [comment]
As per my other notes, the big question is between `MapperFeature` and `DeserializationFeature` -- based on whether this setting can be dynamically changed (yes? Can be added as `DeserializationFeature` or; if not, MUST be `MapperFeature`).

But I think feature can (and should) be added as part of Scala implementation: features must be used when added.

So will leave this issue as the companion for Scala work.

**Comment by pjfanning** [comment]
@cowtowncoder if you don't like this PR, could you suggest an alternative (see https://github.com/FasterXML/jackson-module-scala/pull/521#issuecomment-867553973 as to why adding a jackson-module-scala Module Builder is probably not going to be a workable solution until jackson 3 is released)

**Comment by cowtowncoder** [comment]
@pjfanning I can add this, assuming it will be supported by Scala module for 2.13. I know there is a chicken-and-egg problem here so I am ok merging this first, and seeing how things work wrt 2.13 release (and if need be, just comment it out if nothing in 2.13 would yet use it).

But just to make sure my only concern gets addressed: will it be possible to change this setting across `mapper.readValue()` calls, and to take effect? If yes, I'll merge this.
I ask just because most similar settings related to reflecting and settings in databind change `BeanDeserializer` configuration and due to caching must be set before first use. Scala module probably does not do this, but I want to ask it up front.

**Comment by pjfanning** [comment]
There is already progress on a jackson-module-scala PR - so we should be able to quickly add support once this is merged.

**Comment by pjfanning** [comment]
@cowtowncoder @nick-benoit14 seems it might be better to do this as a MapperFeature

**Comment by nick-benoit14** [comment]
I will open a new PR that adds the mapper feature and change the scala module PR to use that instead

**Comment by cowtowncoder** [comment]
SGTM

**Pull request closed without merging**
