### PR TITLE
Include licensing information in pom.xml

### PR DESCRIPTION
**Pull request by benmccann**
Reports are generated from this information to ensure usage of licenses

### CODE REVIEW

**Comment by cowtowncoder** [comment]
License information actually comes from the parent pom, so it should be accessible.
We try to reduce redundant information if possible, although we also do add a LICENSE directly in jar so that it is somewhat auto-detectible with tools.
But if there are specific reasons why it should be useful to also include license information directly in instance pom, I would be interested in hearing about this.

**Comment by benmccann** [comment]
I was using sbt-license-report to print the license used by all the libraries I use. It wasn't printing anything for Jackson. I closed the issue when I realized it was available in the parent pom and filed an issue with them instead asking them to utilize the parent pom.

**Comment by benmccann** [comment]
Actually, it looks like the culprit is Ivy, which sbt-license-report uses. I filed a bug in their JIRA https://issues.apache.org/jira/browse/IVY-1526

**Comment by cowtowncoder** [comment]
Excellent. Thank you for filing the RFE for the tools involved. I just wanted to make sure the issue you are facing will get resolved.

**Pull request closed without merging**
