### PR TITLE
For tests of LambdaMetafactory (close by end of 2020 if not merged)

### PR DESCRIPTION
**Pull request by jgardo**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
One note: I think that instead of overloading `MethodProperty`, it would probably make more sense to just duplicate it with different name (`MethodHandleProperty` or such), and create different instance based on configuration. Configuration should probably use different setting as `DeserializationFeature` is to allow per-call changes but this is not needed here -- but that is easy enough to change.

I would be interested in getting something like this working for 2.12 as well.

On performance: is the 3% mentioned based on measurements?

**Comment by jgardo** [comment]
Hi @cowtowncoder ,

thanks for reply.

There are some things I have to mention about this pull request:
- main goal of this change was introduce deserialization LambdaMetafactory instead basing on Reflection. There are some articles (e.g. https://www.optaplanner.org/blog/2018/01/09/JavaReflectionButMuchFaster.html ) that sugests that this type of accessing methods is faster than reflection. These articles also suggests that using LambdaMetafactory is much faster than plain MethodHandle and reflection. MethodHandles are in Java 7 is much slower and in Java 8 a little bit slower than reflection.
- unfortunatelly LambdaMetafactory is available since Java 8 and as I know Jackson 2.* requires at least Java 7, so it could be introduced only in Jackson 3.*
- my main goal was to achive much faster accesses to fields than using method reflection by using inlining. However in Jackson context it's very difficult to reach - LambdaMetafactory generates implementation of given interface, so for each method there is an implementation. This makes that each call of method is megamorphic. OpenJDK which is most popular implementation of JVM disabled inlining for megamorphic calls. This is main reason of very limited performance boost.
- only performance benefit of this approach is that checking permissions of accessing method is made once on creating MethodHandles. Reflection checks permission to invoke method every time. 
- performance tests were prepared using JHM. They were executed on my private laptop (Asus S56C with i5-3317U, so it's quite old; on Ubuntu 18.04 without GUI). I used diffrent type of fields - primitives, nonprimitives and mixed. There were also different amount of deserialized fields.
Mentioned 3% was so small performance boost, that it discouraged me from making bigger research.
However there are some sources of these tests: https://github.com/jgardo/jackson-tests
- however personally I see some benefits of rewriting MethodProperty to MethodHandles. I heard that reflection is unwelcome in newer versions of Java. 

Let me know if you're interested in this pull request after all these comments.

**Comment by cowtowncoder** [comment]
@jgardo Ok thank you very much for expanation: this makes more sense. While it is unfortunate expected performance improvement did not pan out, I think it is good to find it out early, and not after implementing and integrating changes. I did have some concerns of my own wrt generation of class per accessor; and based on my own performance testing over time, also know that actual performance often differs from expected, so verification is vital.

Given findings (and wrt 2.x, yes, Java 8 dep), I am not sure it is worth following up on this specific approach then.
I will leave it open for a bit (in case someone else finds it useful), add a note on title, and close eventually.

**Comment by siy** [comment]
My personal experience with LambdaMetafactory (see https://github.com/siy/booter-injector for more details) shows that indeed it is possible to achieve superb performance with it. This approach is about 2 times slower than plain 'new' call. Reflection is about 50 times slower (method handle version is comparable to reflection). Nevertheless, in my case this approach has significant drawback: LambdaMetafactory behaves differently between Java 8 and Java 9+, so I was ought to significantly change code. From my point of view this makes the whole approach not worth the effort. 
Recent version of JDK (15) adds support for hidden classes. I think they can be a better alternative for run-time generation of factory classes. Another alternative is compile-time annotations and annotation processor. Beside other things this way enables completely (runtime) reflection-less processing. Beside better run-time performance, this also paves the way to convenient co-existence with GraalVM.

**Comment by cowtowncoder** [comment]
Does not seem like we are merging this, so closing; may be resurfaced if and when it makes sense.
Jackson 2.x has (and will have) Java 8 baseline, but 3.0 something like Java 17 whenever we get there.

**Pull request closed without merging**
