### PR TITLE
Issue #1313: New IgnoreCase feature to deserialize enums

### PR DESCRIPTION
**Pull request by AnaEliza**
Please let me know if there is something to fix here!
BR.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@AnaEliza Thank you for contributing this! I hope to review this soon, and form quick glance it makes sense.

One (and only) formality we have, before I can merge the patch, is to have a Contributor License Agreement (CLA) filled. It's a short document that affirms that contributor can make contribution under expected terms, and only needs to be filled once for all Jackson projects.
And it keeps legal folks happy (we wouldn't care otherwise) :)

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

The usual way is to print it, fill & sign, scan and email to `info` at fasterxml.com.

Apologies for having to do this, but it really is just one-time thing.

Thank you once again for contributing the patch!

**Comment by AnaEliza** [comment]
@cowtowncoder Hey! I just sent the CLA. Sorry for the huge delay!!!

**Comment by cowtowncoder** [comment]
@AnaEliza No problem, got it, will proceed with merging now.

**Comment by cowtowncoder** [comment]
Actually: I will make one change here -- instead of `DeserializationFeature`, I'll change this to `MapperFeature` to be consistent with existing `MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES`, so we'll have:

    MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS

Change will be in 2.9.0.pr3

**Comment by tea-dragon** [comment]
Mmm this will let me delete another wrapper class. Thanks.

**Comment by nickmafra** [comment]
How to use MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS with @JsonFormat or similar annotation?

**Comment by cowtowncoder** [comment]
@nickmafra I think that would be by using `JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_VALUES`; description suggests it works for Enums too. If not, could you file a new issue pointing out it does not?

**Pull request merged**
