### PR TITLE
findDeserializer of JacksonAnnotationIntrospector  should return Object

### PR DESCRIPTION
**Pull request by smaant**
Pull request for issue https://github.com/FasterXML/jackson-databind/issues/177

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ah. Yes, this would make sense.

One concern I have is with backwards compatibility; I wonder if there is need for defining both for 2.6 (old one being deprecated), use delegation. And then remove old one in 2.7.

**Comment by smaant** [comment]
Oh, I didn't think about backwards compatibility. But, unfortunately, we can't define both of them, because they would differ only by return type.
Although it's possible someone may use this implementation instead of interface, it won't be very hard transition, I think.

**Comment by cowtowncoder** [comment]
No problem, I will try to see if I can do anything to alleviate. My biggest concern really is with binary incompatibility for cases where someone simply upgrades minor version and is overriding old version.
I wish there were good ways to try to find such usage (or lack thereof).
I am not as worried about source (in)compatibility. Sometimes the two differ.

**Comment by cowtowncoder** [comment]
After thinking about it bit more, I see that there really isn't much that can be done here; but also I suspect that bridge methods might solve the potential issue. But the return type should be `Object`.

I also made similar changes to couple of other lookup methods that had not been updated.

**Comment by smaant** [comment]
Awesome, thank you. JacksonAnnotationIntrospector will much more usable with this changes.

**Pull request merged**
