### PR TITLE
Support instantiate bean with Non-default constructor by Using JVM unsafe mechanism 

### PR DESCRIPTION
**Pull request by dylan1108**

### CODE REVIEW

**Comment by dylan1108** [comment]
Using jackson to bean deserializer occur exception， [org.codehaus.jackson.map.JsonMappingException: No suitable constructor found for type]  when non-default constructor supply，Especially in 3rd party class, we could't modify the 3rd party class and can't force the 3rd to comply with this restriction，In This case support the bean deserializer with non-default constructor  will be well received

**Comment by cowtowncoder** [comment]
While I appreciate suggestion, I do not think I want to add uses of Unsafe in core databind code base itself. Its use is not supported and will break with later JDK versions (not sure if it works any more with JDK 11 for example).

But what would be possible, however, is providing this via small extension module, which could provide "default creator", either through `BeanDeserializerModifier.updateBuilder()` (changing `ValueInstantiator` appropriately), probably best way, or via `AnnotationIntrospector.findValueInstantiator()` (but that having possible problem of not knowing when to add use).
I could help in adding such module maybe under `jackson-modules-base`.

**Comment by dylan1108** [comment]
> While I appreciate suggestion, I do not think I want to add uses of Unsafe in core databind code base itself. Its use is not supported and will break with later JDK versions (not sure if it works any more with JDK 11 for example).
> 
> But what would be possible, however, is providing this via small extension module, which could provide "default creator", either through `BeanDeserializerModifier.updateBuilder()` (changing `ValueInstantiator` appropriately), probably best way, or via `AnnotationIntrospector.findValueInstantiator()` (but that having possible problem of not knowing when to add use).
> I could help in adding such module maybe under `jackson-modules-base`.

Thank you for your response, I has clearly knew your warried points  whether JVM can support the feather after JVM 11 version and The jvm unsafe further could't work well in lower JVM version(lower than JDK1.7),and I am looking forward to adding this feature to the module in the near future, thanks for your contributions. for now I customized the jackson simple module to support the bean Polymorphism and bean instantiated with Non-Default constructor.
`import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.ObjectMapper.DefaultTyping;
import com.fasterxml.jackson.databind.deser.BeanDeserializer;
import com.fasterxml.jackson.databind.deser.BeanDeserializerModifier;
import com.fasterxml.jackson.databind.module.SimpleKeyDeserializers;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.type.TypeFactory;

import java.io.IOException;
import java.lang.reflect.Modifier;


public class Jackson_Enhance_Utils {
    private static final ObjectMapper mapper = new ObjectMapper();
    public static final String CLASS_KEY = "@class";
    public static final String BASE_VALUE_KEY = "\"value\"";
    public static final String BASE_VALUE_NODE_KEY = "value";

    public static String serialize(Object obj) throws RuntimeException {
        try {
            return mapper.writeValueAsString(obj);
        } catch (Throwable var2) {
            throw new RuntimeException(var2);
        }
    }

    public static <T> T deserialize(String jsonString, Class<T> clazz) throws RuntimeException {
        try {
            return mapper.readValue(jsonString, clazz);
        } catch (Throwable var3) {
            throw new RuntimeException(var3);
        }
    }

    public static <T> T deserialize(String jsonString, JavaType type) throws RuntimeException {
        try {
            return mapper.readValue(jsonString, type);
        } catch (Throwable var3) {
            throw new RuntimeException(var3);
        }
    }

    public static JsonNode readNode(String jsonString) throws RuntimeException {
        try {
            return mapper.readTree(jsonString);
        } catch (Throwable var2) {
            throw new RuntimeException(var2);
        }
    }

    public static JsonNode valueToTree(Object o) {
        return mapper.valueToTree(o);
    }

    public static TypeFactory typeFactory() {
        return mapper.getTypeFactory();
    }

    static {
        SimpleModule module = new SimpleModule();
        mapper.enableDefaultTypingAsProperty(DefaultTyping.NON_FINAL, "@class");
        module.setKeyDeserializers(new MapKeyDeserializers());
        module.addKeySerializer(Object.class, new MapKeySerializer());
        module.setDeserializerModifier(new MyBeanDeserializerModifier());
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.registerModule(module);
    }

    private  static class MapKeyDeserializers extends SimpleKeyDeserializers {
        private static final KeyDeserializer DEFAULT = new MapKeyDeserializer();
        @Override
        public KeyDeserializer findKeyDeserializer(JavaType type, DeserializationConfig config, BeanDescription beanDesc) {
            KeyDeserializer deserializer = super.findKeyDeserializer(type, config, beanDesc);

            return deserializer != null ? deserializer : DEFAULT;
        }
    }

    private static class MapKeySerializer extends JsonSerializer{
        @Override
        public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            String keyString = Jackson_Enhance_Utils.serialize(value);
            boolean isFinal = Modifier.isFinal(value.getClass().getModifiers());
            StringBuilder key = new StringBuilder();
            if (isFinal) {

                key.append("{\"").append(Jackson_Enhance_Utils.CLASS_KEY).append("\":\"").append(value.getClass().getName()).append("\",");

                if (value instanceof Integer || value instanceof Boolean
                        || value instanceof Byte || value instanceof Short
                        || value instanceof Long || value instanceof Float
                        || value instanceof Double || value instanceof String) {
                    key.append(Jackson_Enhance_Utils.BASE_VALUE_KEY).append(":").append(keyString);
                } else if (value instanceof Enum) {
                    key.append(Jackson_Enhance_Utils.BASE_VALUE_KEY).append(":").append(keyString);
                } else if(value.getClass().isArray()){
                    key.append(Jackson_Enhance_Utils.BASE_VALUE_KEY).append(":").append(keyString);
                } else if (keyString.startsWith("{")) {
                    key.append(keyString.substring(1, keyString.length() - 1));
                } else {
                    key.append(keyString);
                }

                key.append("}");
                keyString = key.toString();
            }
            gen.writeFieldName(keyString);
        }
    }

    private static class MapKeyDeserializer extends KeyDeserializer{
        @Override
        public Object deserializeKey(String key, DeserializationContext ctxt) throws IOException {
            try {
                JsonNode jsonNode = Jackson_Enhance_Utils.readNode(key);
                JsonNode classNode = jsonNode.get(Jackson_Enhance_Utils.CLASS_KEY);
                Class<?> clz = Class.forName(classNode.asText());
                JsonNode valueNode = jsonNode.get(Jackson_Enhance_Utils.BASE_VALUE_NODE_KEY);
                if (clz.equals(Integer.class)) {
                    return Integer.parseInt(valueNode.asText());
                } else if (clz.equals(Boolean.class)) {
                    return Boolean.parseBoolean(valueNode.asText());
                } else if (clz.equals(Byte.class)) {
                    return Byte.parseByte(valueNode.asText());
                } else if (clz.equals(Short.class)) {
                    return Short.parseShort(valueNode.asText());
                } else if (clz.equals(Long.class)) {
                    return Long.parseLong(valueNode.asText());
                } else if (clz.equals(Float.class)) {
                    return Float.parseFloat(valueNode.asText());
                } else if (clz.equals(Double.class)) {
                    return Double.parseDouble(valueNode.asText());
                } else if (clz.equals(String.class)) {
                    return valueNode.asText();
                } else if (clz.isEnum()) {
                    return Jackson_Enhance_Utils.deserialize(valueNode.toString(), clz);
                } else if (clz.isArray()) {
                    return Jackson_Enhance_Utils.deserialize(valueNode.toString(), clz);
                }
                return Jackson_Enhance_Utils.deserialize(key, clz);
            }catch (Exception e){
                throw new IOException("MapKeyDeserializer deserializeKey error",e);
            }
        }
    }
    private static class MyBeanDeserializerModifier  extends BeanDeserializerModifier {
        @Override
        public JsonDeserializer<?> modifyDeserializer(DeserializationConfig config, BeanDescription beanDesc, JsonDeserializer<?> deserializer) {
            //replace default BeanDeserializer to support instantiate bean with Non-default creator.
            if (deserializer instanceof BeanDeserializer) {
                return new MyBeanDeserializer((BeanDeserializer) deserializer);
            }
            return deserializer;
        }
    }

}`

`import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonTokenId;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.deser.BeanDeserializer;
import com.fasterxml.jackson.databind.deser.BeanDeserializerBase;
import com.fasterxml.jackson.databind.deser.SettableBeanProperty;
import sun.misc.Unsafe;

import java.io.IOException;

public class MyBeanDeserializer extends BeanDeserializer{

    public MyBeanDeserializer(BeanDeserializerBase src) {
        super(src);
    }

    @Override
    public Object deserializeFromObjectUsingNonDefault(JsonParser p,DeserializationContext ctxt) throws IOException{
        JsonDeserializer<Object> delegateDeser = _delegateDeserializer;
        if (delegateDeser == null) {
            delegateDeser = _arrayDelegateDeserializer;
        }
        if (delegateDeser != null) {
            return _valueInstantiator.createUsingDelegate(ctxt,
                    delegateDeser.deserialize(p, ctxt));
        }
        if (_propertyBasedCreator != null) {
            return _deserializeUsingPropertyBased(p, ctxt);
        }

       /*
        // 25-Jan-2017, tatu: We do not actually support use of Creators for non-static
        //   inner classes -- with one and only one exception; that of default constructor!
        //   -- so let's indicate it
       //================================= Unsafe Allocator support Bean instantiate with Non default creator,Include the non-static inner class  =======================
       Class<?> raw = _beanType.getRawClass();
        if (ClassUtil.isNonStaticInnerClass(raw)) {
            return ctxt.handleMissingInstantiator(raw, null, p,
                    "can only instantiate non-static inner class by using default, no-argument constructor");
        }*/
        return _deserializeNonDefaultWithUnsafeAllocator(p,ctxt);
        //return ctxt.handleMissingInstantiator(raw, getValueInstantiator(), p,"cannot deserialize from Object value (no delegate- or property-based Creator)");
    }


    private Object _deserializeNonDefaultWithUnsafeAllocator(JsonParser p, DeserializationContext ctxt) throws IOException{
         Unsafe unsafe= UnsafeUtil.getUnsafe();
         Object bean=null;
        try {
            bean = unsafe.allocateInstance(_beanType.getRawClass());
            fillBeanFieldValue(p, ctxt, bean);
        } catch (InstantiationException | IOException e) {
            e.printStackTrace();
            throw new IOException("MapKeyDeserializer deserializeKey error",e);
        }
        return bean;
    }

    private void fillBeanFieldValue(JsonParser p, DeserializationContext ctxt, Object bean) throws IOException {
        p.setCurrentValue(bean);
        if (p.hasTokenId(JsonTokenId.ID_FIELD_NAME)) {
            String propName = p.getCurrentName();
            do {
                p.nextToken();
                SettableBeanProperty prop = _beanProperties.find(propName);
                if (prop != null) { // normal case
                    try {
                        prop.deserializeAndSet(p, ctxt, bean);
                    } catch (Exception e) {
                        wrapAndThrow(e, bean, propName, ctxt);
                    }
                    continue;
                }
                handleUnknownVanilla(p, ctxt, bean, propName);
            } while ((propName = p.nextFieldName()) != null);
        }
    }
}`

**Comment by GedMarc** [comment]
Please Please Please No! Please!

Adding jdk.unsupported module into any new development is a huuuuuuuge no.

The issues surrounding it when using modules in disgusting - this will break pretty much everything for JMS/JDK9 and up.

If that isn't enough to cancel this request, then, no new features should be done on deprecated/removed libraries from the JDK

https://www.oracle.com/technetwork/java/javase/9-removed-features-3745614.html

Please God No

**Comment by GedMarc** [comment]
Or if worst comes to worst, please put this into it's own jackson module, but leave it out of databind or anything that is used globally

**Comment by GedMarc** [comment]
JDK Officially says replace with java.lang.invoke.MethodHandles.Lookup.defineClass

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8193033

**Comment by dylan1108** [comment]
> Or if worst comes to worst, please put this into it's own jackson module, but leave it out of databind or anything that is used globally

Yeah， I have realized that PR is not considered，So I will cancel my pull request，and Customized my deserializer in  the simple module rather than modify the jackson core  code.

**Comment by cowtowncoder** [comment]
@dylan1108 the part about `BeanDeserializer` seems like that would actually work for your use case (I think other parts wrt Maps are for some other uses).

But for more general approach, I would instead try to use `updateBuilder()`, call `builder.getValueInstantiator()`, and see if we have `StdValueInstantiator` that returns `false` for `canCreateUsingDefault()` (so it is typical POJO but one with no zero-argument constructor).

If so could sub-class `StdValueInstantiator`, override `canCreateUsingDefault()` to return `true` and `createUsingDefault()` to use `Unsafe` (or alternate mechanism) for constructing instance.

I think that should work, and avoid fragility of sub-classing `BeanDeserializer`.

**Comment by dylan1108** [comment]
> @dylan1108 the part about `BeanDeserializer` seems like that would actually work for your use case (I think other parts wrt Maps are for some other uses).
> 
> But for more general approach, I would instead try to use `updateBuilder()`, call `builder.getValueInstantiator()`, and see if we have `StdValueInstantiator` that returns `false` for `canCreateUsingDefault()` (so it is typical POJO but one with no zero-argument constructor).
> 
> If so could sub-class `StdValueInstantiator`, override `canCreateUsingDefault()` to return `true` and `createUsingDefault()` to use `Unsafe` (or alternate mechanism) for constructing instance.
> 
> I think that should work, and avoid fragility of sub-classing `BeanDeserializer`.

thanks for your professional guidance. The extension of `ValueInstantiator` is more suitable than the replacement  of `BeanDeserializer` for jackson-databind ,I will  improve my solution and supply the ext-lib for local using before the  `jackson-modules-base` module support

**Comment by cowtowncoder** [comment]
Ended up with slightly different implementation, achieving similar outcome with:

https://github.com/FasterXML/jackson-modules-base/pull/133/

Not sure on diff between `Unsafe` vs `ReflectionFactory`, but like use of module.
(ideally would only replace `ValueInstantiator`, however... we'll see, easier in 3.0)

**Pull request closed without merging**
