### PR TITLE
Fix #3906 by forcing Record constructors to be visible regardless of visibility overrides

### LINKED ISSUE #3906: Regression: 2.15.0 breaks deserialization for records when mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
**Describe the bug**
This code used to work with 2.14.2, but not with 2.15.0
```java
ObjectMapper mapper = new ObjectMapper();
mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
RecordTest recordTest_deserialized = mapper.readValue("{}", RecordTest.class);
```

**Version information**
2.15.0

**To Reproduce**
```java
/**
 * This works fine with Jackson 2.14.2, but not with 2.15.0.
 */
public class Jackson_2_15_0_Regression {

    record RecordTest(String string, int integer) {
    }

    @Test
    public void emptyJsonToRecord() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();

        mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
        // mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);

        RecordTest recordTest_deserialized = mapper.readValue("{}", RecordTest.class);


        System.out.println("RecordTest deserialized: " + recordTest_deserialized);
        Assert.assertEquals(new RecordTest(null, 0), recordTest_deserialized);
    }
}
```
Comment out the `mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE)` and it works.

Note that the commented-out `mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY)` is included in my actual code to get intended behaviour (i.e. only fields are serialized and deserialized, no methods involved), but this did not make any to or from for the problem.

Exception is:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.mats3.examples.jbang.Jackson_2_15_0_Regression$RecordTest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{}"; line: 1, column: 2]

	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1360)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1424)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at io.mats3.examples.jbang.Jackson_2_15_0_Regression.emptyJsonToRecord(Jackson_2_15_0_Regression.java:25)
```

### PR DESCRIPTION
**Pull request by cowtowncoder**
Fixes #3906 as per title.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@yihtserns WDYT?

**Comment by yihtserns** [comment]
As noted by [this comment](https://github.com/FasterXML/jackson-databind/issues/3906#issuecomment-1540978987), private canonical constructor (i.e. for `private record XXX(...) { }`) is visible for deserialization before #3724 (tested & confirmed using `2.14.2`).

Do we want to change `NON_PRIVATE` to `ANY` to preserve that behaviour?

**Comment by yihtserns** [comment]
(Sorry for going MIA with regards to #3906 - besides day job, I was under the impression that it wasn't urgent so I've been researching for a different way to fix that)

**Comment by cowtowncoder** [comment]
@yihtserns Hmmh. Good question. I don't know to be sure; perhaps?

But I also noticed that there's one regression here, for `RecordImplicitCreatorsTest`: doing this will now expose implicit factory methods (`valueOf()`).

And NP for no follow up: I agree that this is not the most important thing to tackle. And with the issues there are maybe another approach would be useful.

**Comment by CatarinaRibas** [comment]
Hi,

Can you please fix this problem? I think this is the reason for some troubles that we have been having.

**Comment by cowtowncoder** [comment]
Unfortunately this breaks some tests. So someone with time should figure out what the problem is, and whether this fix is actually safe to apply or not. I can't (and shouldn't) fix in PR that breaks existing tests.

@CatarinaRibas perhaps you have time to dig into this to help?

Discussion on #3906 side may be a good place to continue discussions on people involved; I created PR but am not most knowledgeable here (nor have time right now)

**Comment by yuzawa-san** [comment]
@cowtowncoder looks the failures are related to [this](https://github.com/FasterXML/jackson-databind/blob/018372e14fa499dfc3be0cfe35f5861fa9dab0d0/src/main/java/com/fasterxml/jackson/databind/cfg/MapperConfigBase.java#L816C18-L816C63). the expected result for that is causing a single test (based around that specific disabled AUTO_DETECT_CREATORS case) to fail.

i got the tests to pass when i changed the condition in the new code to
```java
ClassUtil.isRecordType(baseType) && isEnabled(MapperFeature.AUTO_DETECT_CREATORS)
```

**Comment by cowtowncoder** [comment]
Superceded by #4057 (targeting 2.16, too risky for patch release)

**Pull request closed without merging**
