### PR TITLE
Replaced synchronized HashMap with ConcurrentHashMap in TypeDeserializerBase._findDeserializer

### PR DESCRIPTION
**Pull request by larsp**
- There was contention using `ObjectMapper.readValue(String, Class)` when called from a lot of threads.

We could eliminate the contention here and therefore have a more stable performance when calling `ObjectMapper.readValue(String, Class)` from lots of threads. The `ConcurrentHashMap` is distributing the locks over buckets and in this case probably more important reads can overlap writes. Maybe I am wrong but for me it looks OK to use a `ConcurrentHashMap` here?

Attached screenshot of what we have seen before:
screen shot 2015-06-12 at 12 44 43 pm

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Technically that is possible, but I am bit surprised to find this call as a hot spot. Results should be cached so that these ought to be one-time overhead.
I am not against the change as much as curious as to whether this could be more of a side-effect of lack of reuse of `ObjectMapper`, or something along those lines?

My only concern wrt change would be possible redundant work done on introspection. But that should not lead to correctness issues.

So let me think about this for a bit; it sounds reasonable, but since effects of concurrency changes are difficult to test I want to move carefully.

**Comment by larsp** [comment]
Just double-checked: It is _one_ shared `ObjectMapper` instance shared over all threads.

**Comment by cowtowncoder** [comment]
Ok sounds good, will merge.

**Comment by larsp** [comment]
:+1:  Great! Are there any plans for RC deployments?

**Comment by cowtowncoder** [comment]
2.6.0-rc2 is out, but done before this merge. Still trying to figure out if rc3 is needed before final; probably is since I am still fixing a few things. If so, would it by next weekend I think, goal being 2.6.0 final within June.

**Pull request merged**
