### PR TITLE
Try to merge #4271 (for #1467) to `master` (2 failures wrt Creator name mismatch)

### PR DESCRIPTION
**Pull request by cowtowncoder**
So: hoping to get #4271 merged, but this gets tricky for one specific aspect.
Hoping to get it resolved, otherwise cannot get feature in 3.0.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Hmmmh. So close yet so far. Was able to figure out issue with `renameAll` -- its call had been relocated for 3.0 earlier, so `BeanDeserializerBase` should not need to try to call it.
And of 4 test failures, 2 were for obsolete (but remaining in `3.0`, due to same merge issue), wrt #265, so was able to just remove test class that contains it.

But this leaves 2 remaining test failures that seem legit.
I wonder if you might be able to help see if you spot anything @fxshlein ? I know `3.0` (`master` branch) is quite changed from 2.x and things are moved around.
But any help would be appreciated; I'd really want this feature to work for 3.0 as well as 2.x and we are close :)

cc @JooHyukKim

**Comment by JooHyukKim** [comment]
Seems like a big work we got here :-)
Will try to see what we can do about it, probably tonight!

**Comment by cowtowncoder** [comment]
@JooHyukKim thanks! I'm sure all of us together can figure it out. In the worst case could just move 2 failing tests under "tofix".

**Comment by cowtowncoder** [comment]
Decided to move 2 failing tests under `tofix`; can figure things out in future.

**Pull request merged**
