### PR TITLE
Isolated execution of MapperFootprintTest

### PR DESCRIPTION
**Pull request by yawkat**
Re #3675

Let's see if this works on CI :)

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Note to self: need to merge manually as `pom.xml` does not merge cleanly (I have a setting to ignore changes to avoid bogus failures after releases).

**Comment by cowtowncoder** [comment]
@yawkat What is the invocation to run test set with specific id? (I assume it's not via profile)

**Comment by yawkat** [comment]
@cowtowncoder you can do `mvn :surefire:test@test-footprint`

**Comment by cowtowncoder** [comment]
Ok I will need to add an XML comment in `pom.xml` for that one. Will not remember otherwise, need to stash somewhere :)

**Comment by cowtowncoder** [comment]
@yawkat For some reason I can't make it execute from command-line. As is, I'll get

    No tests to run.

and with something like

    mvn clean package :surefire:test@test-footprint

I get tons of bogus test failures

**Comment by yawkat** [comment]
Oh, that's because it should be `mvn :surefire:test@footprint-test`, not `mvn :surefire:test@test-footprint` :smile: 

And yes, when you just run `mvn test` (i.e. the test phase, not the specific goal or execution), it will run both executions, because I marked both with `<phase>test</phase>`. This way, the workflows don't need updating.

**Pull request merged**
