### PR TITLE
Add enterprise language

### PR DESCRIPTION
**Pull request by phated**
@cowtowncoder I've added the enterprise language in the "Support" section. I also kept the "optional commercial support" language since different audiences might read different sections but I can remove that if you'd like.

Please let me know how this looks and I will apply whatever you decide to the other projects.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
I think it would make sense to combine former Community/Commercial support, maybe changing bulleted list into separate sections: main Jackson portal does it that way:

https://github.com/FasterXML/jackson

and if you want, you could perhaps do another PR for changes to that README as well?

**Comment by phated** [comment]
Perfect! Thanks for pointing that out. I will make the changes to look similar.

You are very quick and I was just typing up an email response, so watch out for that.

**Comment by phated** [comment]
@cowtowncoder how does that look?

**Comment by phated** [comment]
@cowtowncoder let me know if you need any more changes here. I'd like to submit the other PRs by end-of-week.

**Comment by cowtowncoder** [comment]
Looks good, merged!

**Pull request merged**
