### PR TITLE
Json property affects serialization order

### PR DESCRIPTION
**Pull request by pjfanning**
* relates to https://github.com/FasterXML/jackson-databind/issues/3928
* contains https://github.com/FasterXML/jackson-databind/pull/3927 (but that is less contentious and can be added while this is still being discussed)

### CODE REVIEW

**Comment by pjfanning** [comment]
breaks more than it fixes

**Comment by pjfanning** [comment]
I adjusted the change to fix the issues caused to deserialization by my original change - so I've reopened this PR

**Comment by cowtowncoder** [comment]
Hmmmh. There is a reason for including information from Creators during serialization too: all annotations from all accessors should be unified to avoid having to duplicate annotations. Wouldn't this change prevent ability to add necessary annotations in Constructor parameters for serialization purposes (like simple renaming)?

**Comment by cowtowncoder** [comment]
@pjfanning Ok thanks good point wrt fields.
And if this turns out to be problematic we can always revisit (my last remaining suspicion is wrt some user somewhere using explicit setters -- but we do not have an example of such case so that's pure speculation).

I think I can merge this later today.

**Review by cowtowncoder — APPROVED** [review]

**Pull request merged**
