### PR TITLE
README.md: add example treemodel heterogenous operations

### PR DESCRIPTION
**Pull request by jonenst**
Hi,
maybe someone with deeper developper knowledge can proof read this proposed docs.
For me the most important part is to give an example of reading a subfield as a pojo (or list of Pojo), because this corresponds to the very frequent use case where your code models only part of a json document. I added the rest as it felt that it was the right place to showcase the nice shortcut APIs.
This uses 2.16+ functionality for some of the code.
What do you think ?

### CODE REVIEW

**Review by cowtowncoder — APPROVED** [review]
Could possibly by edited a bit more, but I think can be merged as-is as a starting point.
Thanks for sharing!

**Comment by cowtowncoder** [comment]
As per my comment, I'll merged as is -- can be tweaked afterwards, looks useful!

**Comment by jonenst** [comment]
Awesome. Are you planning to do the 2.16 release soon ? These docs are live on the main page https://github.com/FasterXML/jackson-databind but some won't work with latest 2.15.2. I think it's only these two:

```java
 // 2.15
List<Person> friends = mapper.treeToValue(root.get("friends"), mapper.getTypeFactory().constructCollectionType( List.class, Person.class ));
 // more convenient, 2.16+
List<Person> samefriends = mapper.treeToValue(root.get("friends"), new TypeReference<List<Person>>() { });
```

```java
 // 2.15 
root.with("deep").with("large").with("hiearchy").put("important", 42);
 // 2.16+, withObject accepts only jsonpath in 2.15
root.withObject("deep").withObject("large").withObject("hiearchy").put("important", 42);
```

Also I put these 3:
```java
Map<String, Object> dynamicmetadata = Map.of("Some", "Metadata");
root.putPOJO("dynamicmetadata", dynamicmetadata);  // collections
root.putPOJO("dynamicmetadata", mapper.valueToTree(dynamicmetadata)); // same thing
root.set("dynamicmetadata", mapper.valueToTree(dynamicmetadata)); // same thing
```
But maybe the ones with valueToTree could be omitted ? Should valueToTree only be recommended for cases where you need to pass the data to some code that needs a JsonNode input ? I think I lack the global vision to make a good choice here.

**Comment by cowtowncoder** [comment]
Ah. Good point, I moved too fast. Yes, examples should point out minimum version. I do plan on making 2.16.0-rc1 release this week.

**Pull request merged**
