### PR TITLE
Merge functionality of `jackson-module-parameter-names`, dynamically

### LINKED ISSUE #1090: Merge functionality of `jackson-module-parameter-names`, dynamically
It should be possible to start to add Java 8 support in dynamically in Jackson 2.8, but without requiring use of Java 8 -- if running on JDK 7, things should degrade gracefully.

The simplest piece of functionality to merge in should be that of `jackson-module-parameter-names` (see ../../../jackson-module-parameter-names), as it just adds discovery of parameter names.

Another thing that would go well with this would be a new `MapperFeature`, to allow changing of default handling of 1-parameter creators -- default of "delegating" could be overridable. For this, a separate issue should be filed, if and when implementing this RFE.

### PR DESCRIPTION
**Pull request by lpandzic**
Current, basic idea of how #1090 should done.
Was this what you had in mind, @cowtowncoder?

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Not quite. I would get rid of the module and merge functionality straight in `JacksonAnnotationIntrospector`. That would require some care with respect to access to parameter names.

**Comment by lpandzic** [comment]
Well, module is merged in that `ParameterNamesAnnotationIntrospector` is in the source code directly without the module class. Java 8 dependencies must be isolated otherwise you risk ClassNotFound etc.

**Comment by lpandzic** [comment]
@cowtowncoder, I'm also not sure what to do with the tests, do I change them to afront the new behavior or?

**Comment by cowtowncoder** [comment]
Current plan is to fully fold this in `jackson-databind` in 3.0, so closing.

**Pull request closed without merging**
