### PR TITLE
Additional test case for dynamic key serialization.

### PR DESCRIPTION
**Pull request by bimargulies**
This test case fails, and I think it should pass.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ok thanks. I wonder if that is due to use of `JsonNode` kicking of a different path. Will check this out tomorrow.

**Comment by cowtowncoder** [comment]
Interesting. Looks like use of `EnumMap` causes some issues; changing that to `HashMap` allows key serializer to be found.

**Comment by cowtowncoder** [comment]
Quite interesting. For some reason nominal type for key is introspected as `Enum<?>` (which sort of kind of makes sense). So was able to handle that as another special dynamic case; checked the fix in.

**Comment by bimargulies** [comment]
I wonder why my introspective dynamic device didn't fall into that hole?

**Comment by cowtowncoder** [comment]
@bimargulies not sure, but guessing that you had wider applicability?

**Comment by bimargulies** [comment]
I registered mine as the key serializer for Object.class, so that would be
pretty broad.

Anyway, I have no more tests to try after the one I gave you, so I see no
reason to hold back on releasing.

**Pull request merged**
