### PR TITLE
Prevent use of quoted number (index) for Enum deserialization via `MapperFeature.ALLOW_COERCION_OF_SCALARS`

### PR DESCRIPTION
**Pull request by magdel**
Just want to make option to restrict default ability to deserialize any number string as enum value if it is in its ordinal range

### CODE REVIEW

**Comment by f0y** [comment]
Existing behaviour of enum deserialization is absolutely unexpеcted. 
Why do someone want to deserialize string as enum ordinal??

**Comment by cowtowncoder** [comment]
@f0y When using XML, for example, there is no way to reliably detect numbers. Or when using properties. Some (many?) scripting languages have loose type system. In general, every loose handling feature is based on someone requesting (and presumably needing) it.

I am not saying that users should use JSON Strings to contain integer values, but rather just that if the use case is such that one tries to figure out meaning for a String that does not map to known textual values, considering possibility of index value is a viable choice.

But I'll see if any of `DeserializationFeature`s could allow easy configurability here. Preventing such coercion itself is pretty easy of course; I just do not want to break existing use cases.

**Comment by cowtowncoder** [comment]
Modified deserializer to check for `MapperFeature.ALLOW_COERCION_OF_SCALARS`, and if that is disabled (default is enabled), will not consider quoted int value (that is, JSON String containing number) as an index.

**Comment by cowtowncoder** [comment]
Quick note: fix itself is similar to PR -- thank you for submitting it! -- but I try to avoid adding too many specific features at this point (both to keep API bit smaller, and since there are limits for number; beyond 32 need to change impl a bit).

**Comment by f0y** [comment]
Thank you for submitting the fix!

**Comment by magdel** [comment]
Great!

**Comment by cowtowncoder** [comment]
Fwtw, 2.9.0 is now finally released!

**Pull request closed without merging**
