### PR TITLE
Merge junit5 conversion changes from #4362 into master (3.0)

### PR DESCRIPTION
**Pull request by cowtowncoder**
Having some trouble fixing Locale deser tests, will see what CI can show.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@JooHyukKim this is weird. Conversion to `master` (from 2.17) seemed to go fine, but somehow `LocaleDeserTest` broke in some way.

**Comment by JooHyukKim** [comment]
Strange....  as far as I know, all JUnit 5 `Assertions.assertEquals()` message is the THIRD parameter. And also that `expected` and `actual` types are declared explicilty. Maybe that's why?

**Comment by cowtowncoder** [comment]
Code used to have message as 1st argument. Maybe JUnit 4 had that? I fixed ordering for `master`.

**Comment by JooHyukKim** [comment]
> Code used to have message as 1st argument. Maybe JUnit 4 had that? I fixed ordering for `master`.

Oh okay. Maybe something wrong  with Git then? 

I already had the ordering fixed by moving message to third argument in the PR for 2.17 earlier.

**Comment by cowtowncoder** [comment]
Yeah my guess is that maybe there had been 3.0-only changes to that test or something.

Either way it's all good now and next time I'll recognize the issue sooner.

**Pull request merged**
