### PR TITLE
Improve `NullNode.equals()`

### PR DESCRIPTION
**Pull request by dsbecker**
Add support for logical equivalence to NullNode (like other node types have) and also equivalence with java null.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ok. I have bit mixed feelings on users being able to create `NullNode`s, but since that is possible (as per my changing constructor), yes, I concur it should do that.

But I don't think `null` should be allowed as equal.
Instead, method

```java
    public boolean equals(Comparator<JsonNode> comparator, JsonNode other) { ... }
```

should be used for comparisons, and that will allow for custom handling, and was explicitly added to allow use cases like coercions between numeric types and so on.
I think this would be more natural place for `null` coercion as well.

I will go ahead and change `NullNode` equality like suggested.

**Comment by dsbecker** [comment]
When using lists and maps, the contains() implementation uses the object.equals() call. That's the specific case it would have been handy for. But, since there are other solutions (using `@JsonInclude(NON_NULL)` for example) that work, I defer to your judgement since you're much closer to the project. Thanks for listening!

**Comment by dsbecker** [comment]
Close at your leisure. Or would you prefer I update the PR?

**Comment by cowtowncoder** [comment]
Ok, so actually creating custom `NullNode`s would have been difficult before:

1. `NullNode` has (accidentally) left as `final` (I changed that now for 2.10), but no sub-classing possible before
2. Constructor is `protected`

It is possible to create an instance using reflection (or doing split package) but... not sure anyone has actually used it. Also still don't see why someone would do it; perhaps it is necessary by some mock framework or...

**Comment by cowtowncoder** [comment]
@dsbecker I think I can do that, small enough change. Thank you for asking!

**Comment by cowtowncoder** [comment]
Ah, `equals()` used by JDK methods. Fair point.

I hope that ability to create replacements, now, will allow solving that issue.

**Comment by dsbecker** [comment]
Ah, I overlooked the combination of final with protected constructor. My bad.

**Comment by cowtowncoder** [comment]
@dsbecker I did too, it looks like. I don't think I meant to leave `final` in there. :)

**Pull request closed without merging**
