### PR TITLE
Try to fix #4626, #4630 (start with failing tests)

### LINKED ISSUE #4626: `@JsonIgnore` on Record property ignored for deserialization, if there is getter override
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

`@JsonIgnore` on a Record component is ignored when the corresponding accessor method is overridden.

### Version Information

Since `2.15.0`.

### Reproduction

```java
record RecordWithJsonIgnore(int id, @JsonIgnore String name) {
    @Override
    public String name() {
        return name;
    }
}

RecordWithJsonIgnore deser = new ObjectMapper().readValue("{\"id\":123,\"name\":\"Bob\"}", RecordWithJsonIgnore.class);

// failed with:
// org.opentest4j.AssertionFailedError: 
// Expected :RecordWithJsonIgnore[id=123, name=null]
// Actual   :RecordWithJsonIgnore[id=123, name=Bob]
assertEquals(new RecordWithJsonIgnore(123, null), deser);
```

### Expected behavior

_No response_

### Additional context

There are typically 3 places to get an annotation info from:
<table>
<thead>
<tr>
  <th>Where</th>
  <th>For this scenario</th>
</tr>
</thead>
<tbody>
<tr>
<td>Constructor parameter</td>
<td>Can't have <code>@JsonIgnore</code> info because <code>@JsonIgnore</code>'s <code>@Target</code> does not include <code>ElementType.PARAMETER</code> <strong>UPDATE</strong>: Forgot to mention that the hardcoded <code>prop.addCtor(..., false)</code> in <code>POJOPropertiesCollector</code> also needs to be changed for this to work.</td>
</tr>
<tr>
<td>Accessor method</td>
<td>When overridden, <code>@JsonIgnore</code> will not be "inherited" from original method</td>
</tr>
<tr>
<td>Field</td>
<td>#3737 removed field info for deserialization, so it can't contribute the <code>@JsonIgnore</code> info</td>
</tr>
</tbody>
</table>

### PR DESCRIPTION
**Pull request by cowtowncoder**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Not sure this is going anywhere, bumping into issue of #4634, among other problems.

**Comment by cowtowncoder** [comment]
Think I might have solved the problems by only removing Record Fields:

1. After annotations merged AND
2. Only for deserialization (where we shouldn't change value)

**Comment by cowtowncoder** [comment]
@yihtserns WDYT? Looks like this change works, with your earlier fix.

**Comment by yihtserns** [comment]
@cowtowncoder Why still drop the fields, though?  To avoid any other unexpected side-effects?

**Comment by yihtserns** [comment]
Oh right, to avoid a `SettableBeanProperty` (specifically `FieldProperty`) from being created for fields.  OK.

**Comment by cowtowncoder** [comment]
> Oh right, dropping fields to avoid `SettableBeanProperty` (specifically `FieldProperty`) from being created for them. OK.
> 
> Yeah I guess this is a good alternative to #4627.

Correct, so `Field` is never used as mutator for Records (it fixes one specific test).

**Pull request merged**
