### PR TITLE
Possible fix for #1103

### PR DESCRIPTION
**Pull request by aseovic**
This PR fixes the issue I ran into (#1103), but unfortunately breaks `TestTypedDeserialization.testIssue506WithDate` test, and I'm not quite sure how to fix it (it doesn't seem to be working properly anyway, as it writes type information using wrapper array and not as a `type2` property the `@JsonTypeInfo` annotation suggests).

I'm not quite sure what the Issue506 was (doesn't seem to be [this one](https://github.com/FasterXML/jackson-databind/issues/506)), so I have no idea where to look next.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Hmmh. I'll have to actually verify this, since I am not sure this is the correct way to resolve the issue.
Looking at `jackson-datatype-joda`, for example, I'd except more like:

    @Override
    public Object deserializeWithType(JsonParser p, DeserializationContext ctxt, TypeDeserializer typeDeserializer) throws IOException, JsonProcessingException {
        return typeDeserializer.deserializeTypedFromAny(p, ctxt);
    }

**Comment by cowtowncoder** [comment]
Oh, and 506 refers to the old Jackson issue tracker at Codehaus, so it would have been during Jackson 1.x.

**Comment by aseovic** [comment]
All right -- the latest change delegates to super if the current token is START_ARRAY or START_OBJECT, which fixes `TestTypedDeserialization.testIssue506WithDate` issue and allows the test to pass.

**Comment by aseovic** [comment]
Hmm...

I tried `deserializeTypedFromAny`, but it is still failing (although with a slightly different error and stack trace):

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_STRING), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class java.util.Date)
 at [Source: {
  "@class":  "com.fasterxml.jackson.databind.deser.TestDateDeserialization$Person",
  "name":    "Novak Seovic",
  "dateOfBirth": "2007-12-28T00:00:00.000Z"
}; line: 4, column: 18] (through reference chain: com.fasterxml.jackson.databind.deser.Person["dateOfBirth"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:962)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:147)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:82)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserializeWithType(DateDeserializers.java:274)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserializeWithType(DateDeserializers.java:253)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:488)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at com.fasterxml.jackson.databind.deser.TestDateDeserialization.testDateWithTypeDeserializer(TestDateDeserialization.java:66)
```
I believe the problem is that we have a scalar value (String), which needs to be handled by `_parseDate`, as neither `StdScalarDeserializer.deserializeWithType` nor `AsPropertyTypeDeserializer.deserializeTypedFromAny` know how to handle it.

**Comment by aseovic** [comment]
BTW, Java 6 builds are consistently failing in Travis CI, which causes PR checks to fail. Probably makes sense to remove Java 6 build from Travis.

Let me know if you want me to do it and I'll create another PR for it.

**Comment by cowtowncoder** [comment]
@aseovic Thanks -- fixed. I didn't set those up so wasn't aware of need to change. With 2.7, jdk7 is needed to build databind although it still runs on jdk6. Also needed to update branches to build, good to know for future.

**Comment by cowtowncoder** [comment]
Ok, I should have looked at the test first: input JSON does not look right to me. The problem is that I think `Date` properties should be considered typed; not because of default typing, but because of mix-in.
And it must write type as WRAPPER_ARRAY, not property, because Scalar values do not have properties (another theoretical possibility would be WRAPPER_OBJECT, but Jackson choose WRAPPER_ARRAY for simplicity -- for default typing, it must be the same for all types, unless explicitly overridden).

More generally, test should do round-trip handling, as the main intent is that Jackson should always be able to read back serialization it produced (assuming enough root level information is given etc).
So for this test, it would make sense to serialize, deserialize back, ensure correct type, value.

I do think that the type handling for `Date` actually works as expected, from `StdScalarDeserializer`.

About test: it may also be challenging to mix default and explicit typing, although in this case I think that should not cause issues.

**Comment by aseovic** [comment]
I hear you, but will have to disagree for several reasons:

**1. It is inconsistent with how the other scalar types behave**

For example, I added a test that does round-tripping, as you suggested, and also added an `Integer` field to the `Person` class (which is `Comparable`, just like `Date`). When I serialize `Person` instance without the mix-in, I get this:
```json
{"dateOfBirth":"2007-12-28","age":8}
```
However, if I register a mix-in, it impacts `Date` but not the `Integer` field:
```json
{"dateOfBirth":["java.util.Date","2007-12-28"],"age":8}
```
Personally, I don't think `Date` should be serialized any differently either, as type information is completely unnecessary in order to be able to deserialize it -- simple string or integer value would work just as well.

**2. Deserializer should be more lenient**

Regardless of whether we agree on the correct serializer behavior above, there is no reason we shouldn't be able to deserialize both of these representations back into the `Person` instance.

My proposed fix allows exactly that: it will still work if it receives JSON in the second format, but it will also work if it receives the first one. Current implementation doesn't.

I guess the point I'm trying to make is that there is more to JSON than Java or Jackson. While we definitely need to be able to read back what we write, we should also be able to read the correct JSON that comes from a browser JavaScript app, which would most likely be in the first format.

Also, even in the Java ecosystem alone, JSON is commonly used as a data interchange format across multiple applications. It is entirely possible that different applications could have differently configured `ObjectMapper` (with and without mix-in, in this example), but as long as the necessary information is present there is no reason they shouldn't be able to talk to each other.

Anyway, I hope you'll reconsider and include the fix, as it doesn't break anything and simply makes deserializers more lenient. 

BTW, I discovered a few more date-related issues while I was looking into this. I'll open separate issues for them and we can discuss.

**Comment by cowtowncoder** [comment]
With respect to `int`: that is an inconsistency, but not in the way you think: for a small set of Java types, namely `boolean`, `String`, `long`, `double` type info is suppressed. These are called "natural" types. `int` should actually not be one.
This can only be done in case where omission will result in one, and one specific type (or, in case of `boolean`/`Boolean`, wrapper, since reflection will resolve it to either one); types are chosen based on what deserialization into `java.lang.Object` nominal type will give you.

`Date` can not use this, nor can any other type that happens to be JSON scalar; it only occurs for these pre-defined unchangeable types. There are many other such types, like `java.util.UUID`, timezone, monetary values, class names etc etc.
I kind of regret adding this optimization since it confuses things often; and in fact should probably only really be used (if at all) for Strings: savings of that type id are probably more meaningful than others.
But if you consider that aside from this very small set of natural types, EVERYTHING that is to use polymorphic handling must have type id (aside from potential `defaultImpl` for property).

So unfortunately the fix does not work. Unit test breakages are most likely trying to show this; maybe having a look would help illustrate what is expected.

Looking forward to reports on other problems. Date-handling is a big can of worms on Java platform...

**Comment by aseovic** [comment]
I don't know -- the latest fix seems to work fine, with no unit test breakages (thanks for fixing Travis, btw), and the round tripping with type information is still fully supported.

As I said, I don't think making deserializer more lenient is a bad thing. If we have all the type information we need already (and we do), there is no reason to require additional type information in the form of array wrapper.

But ultimately it is your call, and if you don't want to include the fix so be it. I'll have to figure out an alternate way to fix the issue, as it is very much a blocker for me at the moment.

**Comment by cowtowncoder** [comment]
@aseovic How about I'll write a simple test case to show where the breakage would be. It's not that hard. Fix really, really can not work the way proposed. It may work for your usage, I don't doubt that, but I do not see it handling cases that should be supported. And I am more surprised by gap in test coverage, which is my fault. :)

**Comment by cowtowncoder** [comment]
Actually, didn't read the updated patch first, so disregard my comments on this breaking type ids that do exist.

I agree in that this would work with existing types, and in that sense safe.
There are even ways to make it even safer, by whitelisting exceptions (number, String), instead of blacklisting structural tokens (due to various oddities, `FIELD_NAME`, or occasionally closing array/object could also appear).

But I am not convinced that it is reasonably to start adding convenient short-cuts to allow omitting of information in various case, as default handling.

If you want, you can still override default deserializers to add this handling, but in my opinion the default handling should not be too permissive: if type id is required, it should be there, according to encapsulation that is configured. By loosening limitations it is easy for legitimate flaws to be uncovered.

**Comment by aseovic** [comment]
I guess the main point we disagree one is whether type id is required or not. 

In this case I don't think it is, as we have all the information we need to deserialize either string or int scalar into a `java.util.Date`, already know which deserializer to use, etc.

I know I can override default serializers (although in this case it is non-trivial because of `withDateFormat` factory method, which needs to be overridden as well) and make them do whatever I want them to do, and if I was writing an app that uses Jackson that would probably be the simplest thing to do. However, I'm working on an app server/framework that many applications out of my control will use, so the less I have to customize Jackson the better.

Also, that wouldn't help anyone else who runs into similar issue, although you could argue that Jackson has been around for a while and nobody complained about this yet ;-)

**Comment by aseovic** [comment]
And yeah, I wasn't sure if 'black-listing' START-ARRAY/START_OBJECT or 'white-listing' VALUE_STRING/VALUE-NULL/VALUE_NUMBER_INT is better -- I actually had the latter first and then decided to invert it before I committed it :-)

**Comment by aseovic** [comment]
I just merged your new test into my branch and all the tests are still passing, as I expected.

Just to make it clear -- I am not suggesting you should change default _serialization_ behavior. That would be a breaking change, and I don't think any of us (Jackson users) want that. All I'm suggesting is that you make _deserializer_ more permissive so it can deserialize dates (and related types) even if the type information is missing, but can be inferred from the bean property type.

**Comment by aseovic** [comment]
It looks like adding the ComparableMixin wreaks havoc all over the place, so I've removed it and figured out the alternative way to implement the behavior that I need.

Considering that this issue only exists if such mix-in is registered, I agree that there is no need for this fix and will close the PR.

**Comment by cowtowncoder** [comment]
@aseovic Sounds good.

I will keep the idea in mind, however. While I am not yet convinced that more liberal handling is the best way to go about it, I can see why it could be beneficial to allow all scalar-serialized types to do that.
If so, there should be `DeserializationFeature` to allow optional omission of such id, disabled by default, but enabling of which would allow accepting id-less values.

The main concern I really have is that there are cases where allowing this could lead to hiding of error cases: specifically cases where things could arbitrarily work or fail based on whether actual container value set is or is not homogenous, or consisting of certain subset of values.

Anyway: thank you for suggesting the idea. As I said it is good for thought... just takes a while to digest things through, and consider overall impact. Changes in behavior have long-lasting effects and need to be supported for long time to come.

**Pull request closed without merging**
