### PR TITLE
Fix conflicting in POJOPropertiesCollector when having namingStrategy

### PR DESCRIPTION
**Pull request by xiaosunzhu**
swap _renameUsing and trimByVisibility in collectAll().

in _renameUsing will check conflict, but trimByVisibility will filter some conflict, so trimByVisibility before _renameUsing.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@xiaosunzhu First of all, thank you for submitting this patch!

I think I would need at least one test case to show a problem that is resolved by this change (I assume all existing unit tests pass with and without change). This may make sense, but given that the logic is quite sensitive to ordering, I would want to be sure of case(s) being resolved.

**Comment by xiaosunzhu** [comment]
@cowtowncoder 
Ofcourse. I added 2 test cases.

This exception only appears in specific situation, and can also be avoided by modifying code, but logically, it may be better to adjust the order.
I am not sure whether it will cause other problems.

**Comment by cowtowncoder** [comment]
Unfortunately it looks like you reformatted the whole test for some reason and I cannot see the diff in the test case. I would specifically want to see which 2 tests were added.

But I also think that what I would need is an example of user-level problem being solved: it is fine to also test `POJOPropertiesCollector`, but I would want to know at higher level kind of case where ordering of renaming, removal matter.
This because changes in this area have commonly caused problems with some edge case not yet covered by testing, so I want to make sure the problem being solved is real.

**Comment by xiaosunzhu** [comment]
my fault. I revert farmat.

**Comment by cowtowncoder** [comment]
Thank you for the changes, including test case!

**Comment by cowtowncoder** [comment]
@xiaosunzhu Thank you for the fix -- I ended up changing the test slightly (to produce problem from use case, not testing POJOPropertiesCollector), and manually merging -- but the fix is the same.

**Pull request closed without merging**
