### PR TITLE
Pointer based add and remove methods for #392

### PR DESCRIPTION
**Pull request by jgustie**

### CODE REVIEW

**Comment by jgustie** [comment]
I just saw [this](https://groups.google.com/d/topic/jackson-dev/rhkjVcw_FSk/discussion) thread on the dev list about JSON Patch support: it got me wondering where this pull request stands?

I originally introduced these changes because they make something like a JSON Patch implementation pretty easy (in fact that is what originally inspired these changes: I could probably dig that JSON Patch code back up).

**Comment by cowtowncoder** [comment]
@jgustie I think I dropped the ball here.

After thinking about it a bit, I think I am ok with `add` and `remove` for `JsonNode`.
While mutability is not otherwise supported, this seems like acceptable deviation.
Thank you for changes so far, code has improved a lot.

Some remaining issues are:

1. Use of '-'... I assume it comes from JSON Patch? Are semantics used in JSON Path?
2. Exceptions vs returning `false` vs quietly ignoring: I wonder how various errors should be handled. Since most functionality of `JsonNode` will not throw exception (but quietly ignore), it might make sense to either indicate failure (true vs false), or, if applicable, return `MissingNode`. I don't know offhand what makes most sense.

Another that may or may not make sense is to try to get discussion restarted on jackson-dev list.
Timing-wise it should be possible to get developers interested, and this could be one of first 2.7 features.

**Comment by jgustie** [comment]
You and me both, I guess I must have been pretty distracted :)

I tried not to get anything specific from JSON Patch in this part of the implementation: the '-' actually comes from JSON Pointer. It's a reference to the nonexistent member after the last element in an array (the last bullet point in section 4 of RFC 6901). It doesn't make much sense when querying which would explain why it wasn't needed yet.

With the error handling, I only used `MissingNode` internally as a way to raise an exception (i.e. an invalid path will lead to a missing node whose invocation of `add`/`remove` methods always throws `IllegalArgumentException`). Let me know if you think something should be changed.

I'll try picking up the conversation on the dev group to see if anyone bites.

**Comment by cowtowncoder** [comment]
Ah ok wrt '-'. Makes sense with that, was indeed wondering why accessor did not care about it, but makes sense.

Let's go with dev group, wrt error handling. I don't have strong opinion and am interested in hearing if someone has good suggestions there.

**Comment by cowtowncoder** [comment]
Ok, I create #1980 to replace `add()` part (via overload of `with()`), and will create another one for `remove()` (although that needs to go in `ObjectNode`, or maybe `ContainerNode`).

**Pull request closed without merging**
