### PR TITLE
added currently failing version of issue#1351 test

### PR DESCRIPTION
**Pull request by arifogel**
Issue #1351 is not fixed for me. I've added a failing version of the test, with slight modifications from the original test committed for the initial fix. Note that if you change just about any feature of the modified test, the problem goes away. However, I do not have the option in my project to make such modifications, so I really would appreciate if my failing version gets fixed.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Which version?

**Comment by cowtowncoder** [comment]
Ok, will try to see what gives wrt fail and hopefully fix an edge case.

**Comment by cowtowncoder** [comment]
Filed #1417 for follow up; I can reproduce this with latest from `master` and 2.8(.4)

**Comment by cowtowncoder** [comment]
@arifogel Ok, so the problem here is that there is no way to create a default instance of `Issue1351NonBean`, as there is no 0-argument ("default") constructor. Because of this, it is not possibly to (try to) figure out default values for properties. There is nothing I can do about that.
Earlier this would have thrown an exception, but since allowing global default usage, this has not been done with 2.7 or later.

But it is possible that the fallback handling here is wrong: it would seem like `null` should be considered default for `String`; as is, looks like "" is assumed enough, which I don't think makes sense.

So I may be able to fix the specific case here, regardless.

**Comment by arifogel** [comment]
Can this be averted in specific cases by writing a default constructor that
passes "default" values to the jsonconstructor?

**Comment by cowtowncoder** [comment]
@arifogel yes. There just has to be 0-arg constructor (can have any visibility, even `private`), which is called to create an instance; and then property values are accessed using normal rules (getter, field).

**Comment by cowtowncoder** [comment]
Ok. So what happens here is that the default value for String is "", which is why comparison is made.
It gets bit tricky...

**Pull request merged**
