### PR TITLE
Add `JacksonCollectors` with `toArrayNode()` implementation

### PR DESCRIPTION
**Pull request by rikkarth**
See back reference: https://github.com/FasterXML/jackson-databind/pull/4691

cc @cowtowncoder

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks good overall, CLA seems to be sent.

One last thing: I do think name `toArrayNode()` would make sense, given this is what is result of collection. So let's make that one change.

**Comment by rikkarth** [comment]
> Looks good overall, CLA seems to be sent.
> 
> One last thing: I do think name `toArrayNode()` would make sense, given this is what is result of collection. So let's make that one change.

Done as instructed. Thank you.

**Comment by rikkarth** [comment]
Just for future reference future Stream support implementations may include all types of object.

### Example
```java
// don't mind the signature name
// notice the return has changed from JsonNode to String
public static Collector<String, ArrayNode, ArrayNode> someNewSignature(JsonNodeCreator nodeCreator) {
    return Collector.of(
            nodeCreator::arrayNode, // supplier
            ArrayNode::add, // accumulator <---- every type supported by add can become a collector implementation now
            ArrayNode::addAll // combiner
        );
}
```

### Use-Case
```java
@Test
public void testToArrayNsode()
{
    final ObjectMapper objectMapper = new ObjectMapper();

    final JsonNode jsonNodeResult = IntStream.range(0, 10)
        .mapToObj(i -> "Hello")
        .collect(JacksonCollectors.toArrayNodeString());

    System.out.println(jsonNodeResult);
}
```

#### Output
```
["Hello", "Hello", "Hello", "Hello", "Hello", "Hello", "Hello", "Hello", "Hello", "Hello"]
```

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Merged: thank you for contributing this, @rikkarth ! Will be in 2.18.0, to be released within week or so.

**Comment by rikkarth** [comment]
> Merged: thank you for contributing this, @rikkarth ! Will be in 2.18.0, to be released within week or so.

Thank you, you were very supportive and nice, I really appreciate it. I intend to continue supporting you in the future.

**Comment by cowtowncoder** [comment]
Glad this worked out very well; looking forward to our future collaboration @rikkarth !

**Pull request merged**
