### PR TITLE
Add feature to inverse read/write access logic

### LINKED ISSUE #2951: Inverse access of `@JsonProperty(access=)` so it can work differently on server side and client side
@JsonProperty's access mode should be inversed on server side and client side when both sides are sharing the same module class.

when using access = READ_ONLY with @JsonProperty, on the server side, that means property need to be serialized but can't be deserialized. but on the client side, the same property should be able to be deserialized but not to be serialized.

Is it good to have an out-of-box feature to do this inversion?

### PR DESCRIPTION
**Pull request by ggrebert**
This feature is added to fix #2951

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Interesting. Quite simple, I like that. Due to being a new feature, would need to go in 2.13; and I may want to start thinking of better way to configure introspection aspects out of `MapperFeature` (partly since we are now maxed out on possible entries with `int` range).

Thank you for submitting this! It may take a while to get integrated as I am about take bit of a break from Jackson development for December, but I should be able to pick it up early in 2021.

**Comment by ggrebert** [comment]
@cowtowncoder Thx for your comment.

But I don't understand why the build fails on PPC architecture,
and I haven't this kind of equipment to test.

**Comment by cowtowncoder** [comment]
@ggrebert ignore ppc failure for now; it was a recent contribution just merged -- I may have made a mistake with it.

**Comment by cowtowncoder** [comment]
Ok, so:

1. I'd be happy to get this merged in 2.19, but
2. PR is against `master`, so would need to be re-based or re-created.

**Comment by ggrebert** [comment]
replaced by #4761

**Pull request closed without merging**
