### PR TITLE
Fix #1407 (`@JsonFormat.pattern` is ignored for `java.sql.Date` valued properties)

### LINKED ISSUE #1407: `@JsonFormat.pattern` is ignored for `java.sql.Date` valued properties
Hi 
thank you for share a awesome library.

I am using version 2.6.7.
Here is failed test which shows that `@JsonFormat` is ignored `pattern` attribute.

``` java
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;
import java.sql.Date;
import static org.junit.Assert.assertEquals;

public class JsonFormatTest {

    public class Person {
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy.mm.dd")
        public Date dateOfBirth;
    }

    @Test
    public void JsonFormatPatternTest() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        Person i = new Person();
        i.dateOfBirth = Date.valueOf("1980-04-14");
        assertEquals("{\"dateOfBirth\":\"1980.04.14\"}", objectMapper.writeValueAsString(i));
    }
}
```

And the results of running the test:

```
org.junit.ComparisonFailure: 
Expected :{"dateOfBirth":"1980.04.14"}
Actual   :{"dateOfBirth":"1980-04-14"}
```

I don't know exactly the reason.
But I have a doubt in a line of code.
https://github.com/FasterXML/jackson-databind/blob/2.6/src/main/java/com/fasterxml/jackson/databind/ser/std/SqlDateSerializer.java#L36

Which method ignored the `customFormat` param.

Thank you.

### PR DESCRIPTION
**Pull request by sangpire**
Here is the fix for #1407

### CODE REVIEW

**Comment by cowtowncoder** [comment]
First of all, thank you for the PR!

Quick question does this still default to using the odd format that `java.sql.Date.toString()` provides? While odd, that should still happen for backwards compatibility reasons, in my opinion.

**Comment by sangpire** [comment]
No. 

 Default to use the `StdDateFormat.DATE_FORMAT_STR_ISO8601` Pattern.

 The comment means that before changes,
A `SqlDateSerializer` instance's `customFormat` value are always `null`.
So values are serialized by `java.sql.Date.toString()` like the `yyyy-MM-dd` pattern.

 If I create a test with the `yyyy-MM-dd` pattern like others,
that will pass without changes.

 So I use the `yyyy.MM.dd` patters.

 After changes,

**Comment by cowtowncoder** [comment]
@sangpire This would then be breaking change, and I don't think that is warranted. If we were starting from scratch I would agree with the change, but as things are not so much.

So: I would like behavior when there is no custom pattern specified to be the same as with 2.8.

**Comment by sangpire** [comment]
Thank you for finishing.

**Pull request closed without merging**
