### PR TITLE
support LookupCache in TypeFactory (2.12 branch)

### PR DESCRIPTION
**Pull request by pjfanning**
I kept the LRUMap constructors/methods for binary compatibility but can remove those if they are deemed unnecessary.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Actually my main/only concern would be wrt backwards compatibility so I think I'd prefer keeping that for 2.x.
But if you could mark old methods as `@Deprecated` that'd be good, I think?
I also wonder if it'd make sense to switch order of last 2 arguments, just to make it easier to use non-deprecated method without casts (in general it's of course good not to change ordering without good reason).

But there is one thing I'd like changed: I'd prefer not to include `UnlimitedLookupCache` in databind itself: I think using one is asking for trouble and I would not want encourage such use. I am ok with users doing that, just do not want to make it particularly easy (users can already increase maximum size and make effectively unbounded caches) or seem like it was supported use case.
This only concerns inclusion in `jackson-databind`: if it makes sense for Scala module you can of course include it there.

**Comment by pjfanning** [comment]
UnlimitedLookupCache is in the test code and is not part of the main jar - it's just there to allow testing

**Comment by pjfanning** [comment]
I think the compiler should be able to handle having the param list in the same order. I think reordering the param lists would be a little untidy.

**Comment by cowtowncoder** [comment]
Ah, apologies for missing test-class'ness of unlimited cache.

On ordering: yes, compiler can deal with overloads, my only concern is if callers have to add explicit cast to use the non-deprecated version (I think compilers do not typically pay attention to annotations but maybe they do?).

But I guess I can merge this and think about ordering part a bit still.

**Comment by cowtowncoder** [comment]
I guess it's fine to have overloads; they are needed for one-arg cases anyway.
It's probably fine to remove those overloads from 2.13 and only leave public deprecated method(s) (`withCache()`) .

Thank you for backporting this change!

**Pull request merged**
