### PR TITLE
Add support for strict property ordering

### PR DESCRIPTION
**Pull request by siy**
Support for strict property ordering re-applied to 2.12

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you! Apologies for the slow follow up; I just wanted to add a note that I am still following up on this ad plan on getting it included in 2.12 (possibly in 2.12.0-rc2). There is bit of a backlog but I have not forgotten. :-) 

One thing I'd need to merge this (unless I have asked for it already) is CLA from:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

which is usually easiest to do by printing, filling & signing, scan/photo, email to `info` at fasterxml dot com. Only needs to be done once, before the first contribution.

**Comment by cowtowncoder** [comment]
Ok: the change looks good, and once I get CLA I can merge it. I will probably change the name of feature to indicate that it specifically determines whether "Creator properties" get sorted preferentially, but would not override explicit ordering (with `@JsonPropertyOrder`), but other than that it's fine.
I'll actually go ahead and add one explicit test to verify my understanding here is correct.

**Comment by siy** [comment]
Sorry for delays. I'll send signed CLA as soon as I'll be able to reach my printer. Unfortunately I'm in the middle of relocation to another town, so it will take a couple days.

**Comment by cowtowncoder** [comment]
@siy No problem, there is time, thank you for adding an update so I know the state of things.

One thing I have noticed is that some contributors have managed to add signature digitally (getting an image of signature, scanning or probably there's an app for that), paste on pdf document; that's fine for us as well.
So printing part is not absolutely required. I wish we had a better way to handle this in general.

Anyway: thank you for this contribution & we get it merged when we can!

**Comment by siy** [comment]
I did send signed CLA to mentioned above e-mail address.

**Comment by cowtowncoder** [comment]
Thank you -- I finally got to merging this, will go in 2.12.0-rc2.

I renamed property to `MapperFeature.SORT_CREATOR_PROPERTIES_FIRST` (default state `true`), but logic otherwise should be the same.

**Pull request merged**
