### PR TITLE
Adding ppc64le architecture support for travis-ci

### PR DESCRIPTION
**Pull request by kishorkunal-raj**
Hi,
I had added ppc64le support on travis-ci and looks like its been successfully added. I believe it is ready for the final review and merge.

The travis ci build logs can be verified from the link below.
https://travis-ci.com/github/kishorkunal-raj/jackson-databind/builds/181293972
Please have a look.

Thanks!!"

### CODE REVIEW

**Comment by kishorkunal-raj** [comment]
Any views on PR?

**Comment by cowtowncoder** [comment]
@kishorkunal-raj hi there! I am thinking of finalizing 2.12.0 first, releasing it, and could merge it afterwards. I realize this should be harmless (as in not used for actual release) but just due to timing prefer to prevent any possible hickups to Travis builds. But I should be able to get it merged right after, i.e. within a week or so.

**Comment by cowtowncoder** [comment]
Merged; although with severe throttling Travis-ci is doing might mean I'll need to reduce scope of builds in near future.

**Comment by kishorkunal-raj** [comment]
> Merged; although with severe throttling Travis-ci is doing might mean I'll need to reduce scope of builds in near future.

Hi @cowtowncoder,
Thanks for accepting the PR. I noticed you mentioned about throttling issue with travis-ci, I believe it is because we are still using travis-ci.org for CI over here. I would like to suggest to migrate from travis-ci.org to travis-ci.com which has wider range of testing the projects and can resolve the throttling issues. Also to bring into your notice, travis-ci.org is reaching to end of life. 
Hope it will be useful to you.

Thanks!

**Comment by cowtowncoder** [comment]
@kishorkunal-raj thank you; I heard about this transition from others too. I'll see what happens; maybe I'll have some time over holiday break to do transition.

**Pull request merged**
