### PR TITLE
Fix custom comparator container node traversal

### PR DESCRIPTION
**Pull request by danielnorberg**
https://github.com/FasterXML/jackson-databind/issues/1067

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks good to me! 

One quick practical thing: if I haven't asked for CLA earlier (apologies if I have), we'd need one, found here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and it needs to be filled, signed, scanned and email to us (at `info` at fasterxml dot com).
It's a one-time thing, no need for more than one copy in future.

Looking forward to merging this -- I can merge this in 2.6 branch as well.

**Comment by danielnorberg** [comment]
Sure, I'll submit a CLA next week.

**Comment by cowtowncoder** [comment]
Looking forward to it!

**Comment by danielnorberg** [comment]
Submitted!

**Pull request merged**
