### PR TITLE
Declare wrapAndThrows to return an IOException

### PR DESCRIPTION
**Pull request by vjkoskela**
Declare wrapAndThrows to return an IOException to allow callers to use `throw wrapAndThrow(...)` in order to improve readability and code coverage. This is accomplished by forcing the reader and compiler to treat the method call as one branch (it always results in an exception being throw). The change also has the side-effect of ensuring all paths through wrapAndThrow actually throw because they would otherwise be required to return an IOException.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds good. At first I was thinking that name should change, but seeing it actually does also throw (and return signature is just to help with code flow analysis), sounds good.

**Comment by vjkoskela** [comment]
Do you know what release this change will make it into?

**Comment by cowtowncoder** [comment]
Since it was to `master`, after `2.9` release, it would be for 3.0.0-SNAPSHOT.

I'd be bit hesitant to backport signature change in 2.x because it would be nasty combination of source-compatible BUT binary-incompatible changes (have been burnt a few times).
For 2.11 (or even 2.10 patch I suppose) we could add different named version, however, if that was desired, and deprecate old version.

**Comment by vjkoskela** [comment]
Thanks! Not a problem, we are fine waiting on this for 3.x; I was just combing through some issues today and saw this was still pending and wanted to check that it had not fallen through the cracks and the plan had not changed.

**Pull request merged**
