### PR TITLE
fix test code

### PR DESCRIPTION
**Pull request by jinwookh**
fixed 2 failing tests to success, where tests were in databind package.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
For a while I was puzzled since this obviously has not failed in Travis. Until I realized naming convention is off.... and these do fail from IDE.
Thanks!

**Comment by jinwookh** [comment]
Just in curiosity... you're meaning that travis was ignoring these tests then?

**Comment by cowtowncoder** [comment]
@jinwookh yes. Which is why I wasn't aware they were failing after refactoring of exception messages.

**Comment by jinwookh** [comment]
Got it. Thanks for the comment!

**Pull request merged**
