### PR TITLE
Remove usage of _neitherNull on findProperty

### LINKED ISSUE #1912: `BeanDeserializerModifier.updateBuilder()` not work to set custom deserializer on a property (since 2.9.0)
Since `2.9` use `BeanDeserializerModifier.updateBuilder` not work to set custom deserializer on a property.

This is because this method on `BeanDeserializerBase` has bean replace by this : 

old
``` java
public SettableBeanProperty findProperty(String propertyName)
{
    SettableBeanProperty prop = (_beanProperties == null) ?
            null : _beanProperties.find(propertyName);
    if (prop == null && _propertyBasedCreator != null) {
        prop = _propertyBasedCreator.findCreatorProperty(propertyName);
    }
    return prop;
}
```

new 
``` java
    public SettableBeanProperty findProperty(String propertyName)
    {
        SettableBeanProperty prop = (_beanProperties == null) ?
                null : _beanProperties.find(propertyName);
        if (_neitherNull(prop, _propertyBasedCreator)) {
            prop = _propertyBasedCreator.findCreatorProperty(propertyName);
        }
        return prop;
    }

   protected final static boolean _neitherNull(Object a, Object b) {
        return (a != null) && (b != null);
    }
```

`prop == null` has been replace by `prop != null`.

So custom deserializer can not be used and are replaced by default.

### PR DESCRIPTION
**Pull request by deblockt**
Remove usage of _neitherNull on findProperty to get custom property if possible.

close #1912

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for contributing this. Looks legit.

But would it be possible to get a unit test, to show the effect, and guard against regression? (... by refactoring such as the one that broke handling).

**Comment by cowtowncoder** [comment]
One other minor thing: I'm happy to merge this, but one thing we need before the first contribution to Jackson projects is CLA: (unless we already got one -- apologies if I missed earlier one, tried to check)

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

Usual way is to print, fill, sign, scan & email to`info` at fasterxml dot com.
There is also alternative Corporate CLA if you prefer, most contributions are under individual one.

**Comment by deblockt** [comment]
@cowtowncoder I will add unit test.

I have see that master is under 3.0.0-SNAPSHOT version.
If I want this bug to be fixed on the next version of Jackson, which branch should I merge on?

**Comment by cowtowncoder** [comment]
I'd guess this was done for 2.9, so branch would be `2.9`, which is easy to merge to `master` then.
I can handle backporting if need be.

So I just need the CLA, whenever you get a chance (it's just one time thing, not needed for further contributions. But needed since big corporations want to ensure all code contributions are done properly wrt licensing etc).

Thank you again!

**Pull request closed without merging**
