### PR TITLE
Add additional polymorphic test for JSOG deserialization

### PR DESCRIPTION
**Pull request by stickfigure**
Adds a failing test case for polymorphic behavior when using the JSOG id generator. This is roughly equivalent to this (failing) case in the jsog source tree:

https://github.com/jsog/jsog-jackson/blob/master/src/test/java/com/voodoodyne/jackson/jsog/PolymorphicTest.java

### CODE REVIEW

**Comment by cowtowncoder** [comment]
And just to make sure, this is with 2.5.0 right?

**Comment by stickfigure** [comment]
Yes, the released version of 2.5.0.

**Comment by stickfigure** [comment]
Let me clarify that: The test in the jsog-jackson repository runs against the 2.5.0 release. This PR is against HEAD.

**Comment by cowtowncoder** [comment]
Right, mostly verifying it's not an earlier version (2.4). Diffs from 2.5.0 to master (2.6.0-SNAPSHOT) should be small. Although... there are changes so it wouldn't be impossible to see a difference.

**Comment by ericali78** [comment]
Hello,
 Perhaps something related to (in Jackson-databind:deserializeWithType) : 
       ...
        if (_objectIdReader != null) {
            // 05-Aug-2013, tatu: May use native Object Id
            if (p.canReadObjectId()) {
                Object id = p.getObjectId();
                if (id != null) {
                    Object ob = typeDeserializer.deserializeTypedFromObject(p, ctxt);
                    return _handleTypedObjectId(p, ctxt, ob, id);
                }
            }
            // or, Object Ids Jackson explicitly sets
            JsonToken t = p.getCurrentToken();
            // for now (2.2.x) we only allow scalar types (Strings, integral numbers):
            // NOTE: may  need to allow handling of structured values in future for JSOG
            if (t != null && (t.isScalarValue() || _objectIdReader.maySerializeAsObject())) {
                //t.is
                Object o= deserializeFromObjectId(p, ctxt);

**Comment by cowtowncoder** [comment]
Hmmh. Indeed, that is the problematic part. This may be a royal pain to resolve...

**Comment by ericali78** [comment]
I tried to manage thing like this :
in JSOGRefDeserializer, if not able to decode a @ref then return null value , then in the caller (Object o= deserializeFromObjectId(p, ctxt);) , o is null so we could try deserialize object instead of objectId. The fact is that currentToken is not at he start of object (since already readed if jsogDeserializer). We’d need kind of buffering to be able to reply the deserialization at the start of object … or to have kind o ‘rewind’ function to set back the current token to start of object …

**Comment by cowtowncoder** [comment]
No sweat, I was actually able to solve it. And indeed part of the problem is that token state with typed deser was not yet `FIELD_NAME`. Fix will be in 2.5.1.

**Comment by ericali78** [comment]
Great job
Thank you

**Pull request merged**
