### PR TITLE
Use HashSet's initialCapacity in arrayToSet method

### PR DESCRIPTION
**Pull request by privettoli**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thanks -- I added it along these lines.

**Comment by privettoli** [comment]
@cowtowncoder, then you should add a check 'elements' for null

**Comment by privettoli** [comment]
@cowtowncoder, we should definitely remove the NPE. I closed the pull request as soon as I realized that there's NPE

**Comment by cowtowncoder** [comment]
@privettoli No problem, check is done in source code -- did not use patch exactly as is, just added size indicator.

**Pull request closed without merging**
