### PR TITLE
[databind#1433] ObjectMapper.convertValue no longer shortcuts nulls.

### PR DESCRIPTION
**Pull request by jdmichal**
This allows primitive conversions to assume the default value.
It also allows deserializer getNullValue hooks to function as intended.

### CODE REVIEW

**Comment by jdmichal** [comment]
Pull request to fix #1433.

**Comment by cowtowncoder** [comment]
Hmmh. Interesting. I would like to see much better test coverage, however, to know it won't give NPEs for other types.

**Comment by jdmichal** [comment]
Added more testing. Are there any other tests you would want to see? There's only so many things to test when the only input is `null`, and I can't think of anything else.

(Also, sorry for rewriting the original commit. Had to correct the user information.)

**Comment by cowtowncoder** [comment]
@jdmichal That's a good start, I think it'd be good to see how a simple POJO would fare, I think. Something other than primitive/wrapper. If that works as before, returns null, I think that's good.

**Comment by cowtowncoder** [comment]
Aside from POJO test, one more thing: assuming I haven't yet asked for it (apologies if I have), we need Contributor License Agreement (CLA) before first contribution (but not after possible subsequent ones, i.e. covers all contributions). Document is here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and usually it's easiest to print, fill & sign, then scan or take photo, and email to `info` at fasterxml dot com. Once we have received it, I can merge the patch in. Looking forward to doing that, thank you in advance!

**Comment by cowtowncoder** [comment]
Ok one more thing: POJO tests seem to set null value to not null: it's good to test that case, but what I am really most interested in is the common case where user hasn't done anything, and JSON `null` will be returned as `null`. As long as that still works I'm ok with the change.

**Comment by jdmichal** [comment]
Agreement signed and sent.

I'm unsure exactly what you mean. `null` to `null` is what the first two assertions test in `TestBeanConversions` ([source](https://github.com/FasterXML/jackson-databind/pull/1435/files#diff-aa3dce516b99905be067966ba82a6015R277)).

**Comment by cowtowncoder** [comment]
@jdmichal Thanks!

As to test: POJOS included seem to have deserializers with overriden `getNullValue()` that returns something other than `null`? If so all I mean is that it'd be good to also test stock POJO with no custom deserializer at all. If I misread code, my mistake.

**Comment by jdmichal** [comment]
Do these first two tests not cover that case ([source](https://github.com/FasterXML/jackson-databind/pull/1435/files#diff-aa3dce516b99905be067966ba82a6015R277))? I don't see any deserializer mapping for either of these:

```java
// Test null conversions from [databind#1433]
public void testConversionIssue1433() throws Exception
{
    assertNull(MAPPER.convertValue(null, Object.class));
    assertNull(MAPPER.convertValue(null, PointZ.class));

    assertSame(NullBean.NULL_INSTANCE, MAPPER.convertValue(null, NullBean.class));
}
```

**Comment by cowtowncoder** [comment]
@jdmichal Ah ok. Yes, second one should cover it. (first one not, since `Object` is bit special due to ... reasons). Thanks!

**Pull request merged**
