### PR TITLE
Fix #2001 remove renamed properties from ignored

### LINKED ISSUE #2001: Deserialization issue with `@JsonIgnore` and `@JsonCreator` + `@JsonProperty` for same property name
Issue originally found on jackson-module-kotlin: https://github.com/FasterXML/jackson-module-kotlin/issues/124. Issue reproducible with Java code.

Entity class:
```java
static public class Foo {
  @JsonIgnore 
  public String query;

  @JsonCreator
  @ConstructorProperties("rawQuery")
  public Foo(@JsonProperty("query") String rawQuery) {
    query = rawQuery;
  }
}
```

Fails this test:
```java
Foo deserialized = new ObjectMapper().readValue("{\"query\": \"bar\"}", Foo.class);
assertEquals("bar", deserialized.query);
```

### PR DESCRIPTION
**Pull request by jskierbi**
Issue: https://github.com/FasterXML/jackson-databind/issues/2001

Original issue found and reported in jackson-module-kotlin:
https://github.com/FasterXML/jackson-module-kotlin/issues/124

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for submitting this. I assume all existing tests still pass with the fix?
(I can test locally)

**Comment by jskierbi** [comment]
Yes, seems so - all existing tests green on master still green with the fix.

**Comment by cowtowncoder** [comment]
Ok. So, the only other thing I need is CLA (unless I have asked and received one earlier, apologies if so we have a few collected over the years):

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

it's one-pager, and usually easiest way is to print, fill & sign, scan, email to `info` at fasterxml dot com.
Once this is done I can merge. It's the only piece of process we have, and CLA is good for all future contributions for Jackson projects.

Thank you for the fix!

**Comment by jskierbi** [comment]
It's been sent 👍

**Pull request merged**
